#include "emitter.h"

#include <cctype>
#include <iostream>
#include <sstream>
#include <typeinfo>
#include <utility>

namespace cppfort::stage0 {
namespace {
std::string normalize_space(std::string text) {
    std::string result;
    bool in_space = false;
    for (char c : text) {
        if (std::isspace(static_cast<unsigned char>(c))) {
            if (!in_space) {
                result.push_back(' ');
                in_space = true;
            }
        } else {
            result.push_back(c);
            in_space = false;
        }
    }
    if (!result.empty() && result.front() == ' ') {
        result.erase(result.begin());
    }
    if (!result.empty() && result.back() == ' ') {
        result.pop_back();
    }
    return result;
}

std::string trim_copy(std::string text) {
    while (!text.empty() && std::isspace(static_cast<unsigned char>(text.front()))) {
        text.erase(text.begin());
    }
    while (!text.empty() && std::isspace(static_cast<unsigned char>(text.back()))) {
        text.pop_back();
    }
    return text;
}

// Fix simple cpp2 type/expr idioms into valid C++ forms.
// Examples:
//  - type: "*std::string" -> "std::string*"
//  - expr: "s&" -> "&s"
//  - expr: "ps* = ..." -> "*ps = ..."
//  - simple UFCS pattern: ":cout << ... std" -> "std::cout << ..."
std::string fix_prefix_type(std::string type) {
    // move leading '*' and '&' to the end
    std::string prefix;
    while (!type.empty() && (type.front() == '*' || type.front() == '&')) {
        prefix.push_back(type.front());
        type.erase(type.begin());
    }
    // append in reverse order for readability: '*' then '&'
    for (char c : prefix) {
        if (c == '*') type += '*';
        else if (c == '&') type += '&';
    }
    return type;
}

std::string fix_expression_tokens(std::string expr) {
    // Simple postfix deref: identifier* -> *identifier
    // Use a manual scan to avoid regex dependency
    for (size_t pos = 0; pos + 1 < expr.size(); ++pos) {
        if (std::isalnum(static_cast<unsigned char>(expr[pos])) || expr[pos] == '_') {
            // find end of ident
            size_t start = pos;
            while (pos < expr.size() && (std::isalnum(static_cast<unsigned char>(expr[pos])) || expr[pos] == '_')) ++pos;
            if (pos < expr.size() && expr[pos] == '*') {
                std::string ident = expr.substr(start, pos - start);
                // replace ident* with *ident
                expr.replace(start, ident.size() + 1, std::string("*") + ident);
                // continue after the inserted sequence
                pos = start + 1 + ident.size();
            }
        }
    }

    // Simple address-of suffix: something& -> &something (only for simple tokens)
    for (size_t pos = 0; pos + 1 < expr.size(); ++pos) {
        if ((std::isalnum(static_cast<unsigned char>(expr[pos])) || expr[pos] == '_') && expr[pos+1] == '&') {
            // find start of ident
            size_t end = pos;
            size_t start = pos;
            while (start > 0 && (std::isalnum(static_cast<unsigned char>(expr[start-1])) || expr[start-1] == '_')) --start;
            std::string ident = expr.substr(start, end - start + 1);
            // replace ident& with &ident
            expr.replace(start, ident.size() + 1, std::string("&") + ident);
            pos = start + 1 + ident.size();
        }
    }

    // Simple UFCS pattern: find a ' std' token and a preceding ':id'
    size_t std_pos = expr.find(" std");
    if (std_pos != std::string::npos) {
        // find last ':' before std_pos
        size_t col_pos = expr.rfind(':', std_pos);
        if (col_pos != std::string::npos && col_pos + 1 < expr.size()) {
            // read identifier after ':'
            size_t id_start = col_pos + 1;
            size_t id_end = id_start;
            while (id_end < expr.size() && (std::isalnum(static_cast<unsigned char>(expr[id_end])) || expr[id_end] == '_')) ++id_end;
            if (id_end > id_start) {
                std::string id = expr.substr(id_start, id_end - id_start);
                // remove the ':id' and the ' std' and replace with 'std.id'
                expr.erase(std_pos, 4); // remove " std"
                expr.erase(col_pos, id.size() + 1); // remove ":id"
                expr.insert(col_pos, std::string("std.") + id);
            }
        }
    }

    return expr;
}
}

std::string Emitter::emit(const TranslationUnit& unit, const EmitOptions& options) const {
    std::string output;
    if (options.include_preamble) {
        output += "// Generated by cppfort stage0 transpiler\n";
        output += "#include <cstdint>\n";
        output += "#include <iostream>\n";
        output += "#include <string>\n";
        output += "#include <string_view>\n";
        output += "#include <vector>\n\n";
        // Cpp2 type aliases
        output += "using i8 = std::int8_t;\n";
        output += "using i16 = std::int16_t;\n";
        output += "using i32 = std::int32_t;\n";
        output += "using i64 = std::int64_t;\n";
        output += "using u8 = std::uint8_t;\n";
        output += "using u16 = std::uint16_t;\n";
        output += "using u32 = std::uint32_t;\n";
        output += "using u64 = std::uint64_t;\n\n";
    }

    bool first = true;
    for (const auto& type : unit.types) {
        if (!first) {
            output += '\n';
        }
        emit_type(type, output, 0);
        first = false;
    }

    for (const auto& fn : unit.functions) {
        if (!first) {
            output += '\n';
        }
        emit_function(fn, output, 0);
        first = false;
    }

    return output;
}

void Emitter::emit_function(const FunctionDecl& fn, std::string& out, int indent) const {
    auto return_type = fn.return_type.has_value() && !fn.return_type->empty()
        ? normalize_space(*fn.return_type)
        : std::string {"void"};

    // Special handling for main: must return int
    bool is_main = fn.name == "main";
    if (is_main && return_type == "void") {
        return_type = "int";
    }

    auto emit_param_type = [this](const Parameter& param) {
        auto type = normalize_space(param.type);
        if (type.empty()) {
            type = "auto";
        }
        // canonicalize prefix pointer styles like '*T'
        type = fix_prefix_type(type);
        switch (param.kind) {
            case ParameterKind::In:
                return std::string("cpp2::impl::in<") + type + ">";
            case ParameterKind::InOut:
            case ParameterKind::Out:
                return type + "&";
            case ParameterKind::Copy:
                return std::string("cpp2::impl::copy<") + type + ">";
            case ParameterKind::Move:
                return std::string("cpp2::impl::move<") + type + ">";
            case ParameterKind::Forward:
                return type + "&&";
            case ParameterKind::Default:
            default:
                return type;
        }
    };

    std::ostringstream signature;
    signature << "auto " << fn.name << "(";
    for (std::size_t i = 0; i < fn.parameters.size(); ++i) {
        if (i != 0) {
            signature << ", ";
        }
        const auto& param = fn.parameters[i];
        auto ptype = emit_param_type(param);
        signature << ptype << ' ' << param.name;
    }
    signature << ") -> " << return_type << ' ';

    // Emit a debug comment with parameter kinds (helps validate parser wiring)
    signature << "/*kinds:";
    for (std::size_t i = 0; i < fn.parameters.size(); ++i) {
        if (i) signature << ",";
        switch (fn.parameters[i].kind) {
            case ParameterKind::In: signature << "In"; break;
            case ParameterKind::InOut: signature << "InOut"; break;
            case ParameterKind::Out: signature << "Out"; break;
            case ParameterKind::Copy: signature << "Copy"; break;
            case ParameterKind::Move: signature << "Move"; break;
            case ParameterKind::Forward: signature << "Forward"; break;
            default: signature << "Default"; break;
        }
    }
    signature << "*/";

    Emitter::append_line(out, signature.str() + "{", indent);

        if (std::holds_alternative<Block>(fn.body)) {
        emit_block(std::get<Block>(fn.body), out, indent + 1, is_main && return_type == "int");
    } else {
        const auto& expr = std::get<ExpressionBody>(fn.body);
        std::string line;
        auto fixed = fix_expression_tokens(normalize_space(expr.expression));
        if (return_type == "void") {
            line = fixed + ';';
        } else {
            line = "return " + fixed + ';';
        }
        Emitter::append_line(out, line, indent + 1);
    }

    Emitter::append_line(out, "}", indent);
}

void Emitter::emit_type(const TypeDecl& type, std::string& out, int indent) const {
    std::ostringstream signature;
    signature << "class " << type.name << " {";
    Emitter::append_line(out, signature.str(), indent);

    // For now, emit the body as-is, assuming it's C++ code
    // TODO: Parse and emit proper Cpp2 type members
    std::string body = normalize_space(type.body);
    if (!body.empty()) {
        Emitter::append_line(out, body, indent + 1);
    }

    Emitter::append_line(out, "};", indent);
}

void Emitter::emit_block(const Block& block, std::string& out, int indent, bool add_return_0) const {
    for (const auto& stmt : block.statements) {
        emit_statement(stmt, out, indent);
    }
    if (add_return_0) {
        Emitter::append_line(out, "return 0;", indent);
    }
}

void Emitter::emit_statement(const Statement& stmt, std::string& out, int indent) const {
    std::visit([
        &out,
        indent
    ](const auto& node) {
        using T = std::decay_t<decltype(node)>;
        if constexpr (std::is_same_v<T, VariableDecl>) {
            auto type = normalize_space(node.type);
            if (type.empty()) {
                type = "auto";
            }
            std::string line = type + ' ' + node.name;
            if (node.initializer.has_value() && !node.initializer->empty()) {
                auto init = fix_expression_tokens(normalize_space(*node.initializer));
                line += " = " + init;
            }
            line += ';';
            Emitter::append_line(out, line, indent);
        } else if constexpr (std::is_same_v<T, ExpressionStmt>) {
            Emitter::append_line(out, fix_expression_tokens(normalize_space(node.expression)) + ';', indent);
        } else if constexpr (std::is_same_v<T, ReturnStmt>) {
            if (node.expression.has_value() && !node.expression->empty()) {
                Emitter::append_line(out, "return " + normalize_space(*node.expression) + ';', indent);
            } else {
                Emitter::append_line(out, "return;", indent);
            }
        } else if constexpr (std::is_same_v<T, AssertStmt>) {
            Emitter::append_line(out, "assert(" + normalize_space(node.condition) + ");", indent);
        }
    }, stmt);
}

void Emitter::append_line(std::string& out, std::string_view text, int indent) {
    out.append(indent_string(indent));
    out.append(text);
    out.push_back('\n');
}

std::string Emitter::indent_string(int indent) {
    constexpr int spaces_per_indent = 4;
    return std::string(static_cast<std::size_t>(indent * spaces_per_indent), ' ');
}

} // namespace cppfort::stage0
