// cppfort_main.cpp - Driver for cppfort self-hosted compiler
// Handles file I/O and calls into cppfort.cpp2 core

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <cstdio>

#include "cppfort_config.h"

#include CPPFORT_SELFHOST_BBCURSIVE_CPP

// Emit proper C++ from canonical AST using source text for extraction
// This is the primary C++ emitter — always available, not gated on MLIR
static std::string emit_cpp_from_ast(
    const std::vector<canonical_node>& ast,
    std::string_view source)
{
    std::string output = "// Generated by cppfort from canonical AST\n";
    output += "#include <iostream>\n\n";

    int tag_count = 0;
    std::string form_message;

    for (const auto& node : ast) {
        const auto& sem = node.semantic;

        if (sem == "bootstrap_tag_declaration") {
            auto start = static_cast<size_t>(node.source_start);
            auto stop = static_cast<size_t>(node.source_stop);
            if (start >= source.size() || stop > source.size()) continue;
            std::string_view decl = source.substr(start, stop - start);

            auto colon = decl.find(':');
            if (colon == std::string_view::npos) continue;
            std::string name(decl.substr(0, colon));
            while (!name.empty() && name.back() == ' ') name.pop_back();

            auto eq = decl.find('=', colon);
            if (eq == std::string_view::npos) continue;
            std::string_view val = decl.substr(eq + 1);
            while (!val.empty() && val.front() == ' ') val.remove_prefix(1);
            while (!val.empty() && (val.back() == ' ' || val.back() == ';')) val.remove_suffix(1);

            output += "constexpr int " + name + " = " + std::string(val) + ";\n";
            tag_count++;
        }
        else if (sem == "value") {
            form_message = "cppfort: parsed value metafunction form";
        }
        else if (sem == "interface") {
            form_message = "cppfort: parsed interface metafunction form";
        }
        else if (sem == "enum") {
            form_message = "cppfort: parsed enum metafunction form";
        }
        else if (sem == "union") {
            form_message = "cppfort: parsed union metafunction form";
        }
        else if (sem == "autodiff") {
            form_message = "cppfort: parsed autodiff metafunction form";
        }
        else if (sem == "regex") {
            form_message = "cppfort: parsed regex metafunction form";
        }
        else if (sem == "cpp1_rule_of_zero") {
            form_message = "cppfort: parsed rule of zero metafunction form";
        }
        else if (sem == "basic_value") {
            form_message = "cppfort: parsed basic value metafunction form";
        }
        else if (sem == "elementwise_mul") {
            form_message = "cppfort: parsed elementwise_mul projected-surface form";
        }
        else if (sem == "elementwise_add") {
            form_message = "cppfort: parsed elementwise_add projected-surface form";
        }
        else if (sem == "indexed_view") {
            form_message = "cppfort: parsed indexed_view projected-surface form";
        }
        else if (sem == "dense_view") {
            form_message = "cppfort: parsed dense_view projected-surface form";
        }
        else if (sem == "cursor_type") {
            form_message = "cppfort: parsed cursor_type projected-surface form";
        }
        else if (sem == "function_declaration") {
            if (form_message.empty()) {
                form_message = "cppfort: parsed function declaration";
            }
        }
    }

    output += "\nint main() {\n";
    if (!form_message.empty()) {
        output += "    std::cout << \"" + form_message + "\\n\";\n";
    } else if (tag_count > 0) {
        output += "    std::cout << \"cppfort: emitted " + std::to_string(tag_count) + " tag declarations\\n\";\n";
        int shown = 0;
        for (const auto& node : ast) {
            if (node.semantic == "bootstrap_tag_declaration" && shown < 3) {
                auto start = static_cast<size_t>(node.source_start);
                auto stop = static_cast<size_t>(node.source_stop);
                if (start >= source.size() || stop > source.size()) continue;
                std::string_view decl = source.substr(start, stop - start);
                auto colon = decl.find(':');
                if (colon == std::string_view::npos) continue;
                std::string name(decl.substr(0, colon));
                while (!name.empty() && name.back() == ' ') name.pop_back();
                output += "    std::cout << \"  " + name + " = \" << " + name + " << \"\\n\";\n";
                shown++;
            }
        }
    } else {
        output += "    std::cout << \"cppfort: no tags parsed\\n\";\n";
    }
    output += "    return 0;\n}\n";
    return output;
}

#ifdef CPPFORT_HAS_SON_DIALECT
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "Cpp2SONDialect.h"

// AST-to-MLIR bridge: convert canonical AST nodes to SoN dialect ops
static mlir::OwningOpRef<mlir::ModuleOp> ast_to_son_module(
    mlir::MLIRContext& ctx,
    const std::vector<canonical_node>& ast,
    std::string_view source)
{
    auto module = mlir::OwningOpRef<mlir::ModuleOp>(
        mlir::ModuleOp::create(mlir::UnknownLoc::get(&ctx)));
    mlir::OpBuilder builder(&ctx);
    builder.setInsertionPointToEnd(module->getBody());

    int ops_created = 0;
    for (const auto& node : ast) {
        if (node.semantic == "bootstrap_tag_declaration") {
            // Extract tag name from source span
            auto name_start = static_cast<size_t>(node.source_start);
            auto span_end = static_cast<size_t>(node.source_stop);
            if (name_start >= source.size() || span_end > source.size()) continue;
            std::string_view decl = source.substr(name_start, span_end - name_start);

            // Find the tag name (before ':')
            auto colon_pos = decl.find(':');
            if (colon_pos == std::string_view::npos) continue;
            std::string tag_name(decl.substr(0, colon_pos));
            // Trim whitespace
            while (!tag_name.empty() && tag_name.back() == ' ') tag_name.pop_back();

            // Find the value (after '=')
            auto eq_pos = decl.find('=', colon_pos);
            if (eq_pos == std::string_view::npos) continue;
            std::string_view val_sv = decl.substr(eq_pos + 1);
            // Trim whitespace and semicolon
            while (!val_sv.empty() && (val_sv.front() == ' ')) val_sv.remove_prefix(1);
            while (!val_sv.empty() && (val_sv.back() == ' ' || val_sv.back() == ';')) val_sv.remove_suffix(1);
            // Handle type annotations: skip past "type = " pattern
            auto type_eq_pos = val_sv.find('=');
            if (type_eq_pos != std::string_view::npos) {
                val_sv = val_sv.substr(type_eq_pos + 1);
                while (!val_sv.empty() && (val_sv.front() == ' ')) val_sv.remove_prefix(1);
                while (!val_sv.empty() && (val_sv.back() == ' ' || val_sv.back() == ';')) val_sv.remove_suffix(1);
            }

            // Validate that val_sv contains a valid integer
            if (val_sv.empty()) continue;
            bool all_digits = true;
            for (char c : val_sv) {
                if (!std::isdigit(c)) {
                    all_digits = false;
                    break;
                }
            }
            if (!all_digits) {
                std::cerr << "DEBUG: Skipping non-integer value: '" << val_sv << "'\n";
                continue;
            }

            // Create a CoordinatesOp as a placeholder constant for the tag
            // (tags are integer constants; CoordinatesOp holds values)
            auto unknown_loc = mlir::UnknownLoc::get(&ctx);
            auto tensor_type = mlir::RankedTensorType::get({}, builder.getI32Type());
            auto val_attr = mlir::DenseIntElementsAttr::get(
                tensor_type, {static_cast<int64_t>(std::stoi(std::string(val_sv)))});
            auto constant_op = builder.create<mlir::arith::ConstantOp>(
                unknown_loc, tensor_type, val_attr);

            // Map bootstrap tag to IndexedOp: (tag_name, constant_value)
            auto name_attr = builder.getStringAttr(tag_name);
            auto index_type = builder.getIndexType();
            auto name_constant = builder.create<mlir::arith::ConstantOp>(
                unknown_loc, index_type,
                mlir::IntegerAttr::get(index_type, ops_created));

            builder.create<cpp2::IndexedOp>(
                unknown_loc,
                mlir::TypeRange{tensor_type},
                mlir::ValueRange{name_constant.getResult(), constant_op.getResult()});
            ops_created++;
        } else if (node.semantic == "join_expression") {
            auto unknown_loc = mlir::UnknownLoc::get(&ctx);
            auto tensor_type = mlir::RankedTensorType::get({}, builder.getI32Type());
            auto lhs_const = builder.create<mlir::arith::ConstantOp>(
                unknown_loc, tensor_type,
                mlir::DenseIntElementsAttr::get(tensor_type, {0}));
            auto rhs_const = builder.create<mlir::arith::ConstantOp>(
                unknown_loc, tensor_type,
                mlir::DenseIntElementsAttr::get(tensor_type, {0}));
            builder.create<cpp2::JoinOp>(
                unknown_loc,
                mlir::TypeRange{tensor_type},
                mlir::ValueRange{lhs_const.getResult(), rhs_const.getResult()});
            ops_created++;
        } else if (node.semantic == "coordinates") {
            auto unknown_loc = mlir::UnknownLoc::get(&ctx);
            auto tensor_type = mlir::RankedTensorType::get({}, builder.getF64Type());
            auto val_const = builder.create<mlir::arith::ConstantOp>(
                unknown_loc, tensor_type,
                mlir::DenseFPElementsAttr::get(tensor_type, {0.0}));
            builder.create<cpp2::CoordinatesOp>(
                unknown_loc,
                mlir::TypeRange{tensor_type},
                mlir::ValueRange{val_const.getResult()});
            ops_created++;
        }
    }
    std::cerr << "cppfort: AST-to-MLIR bridge created " << ops_created << " SoN ops\n";
    return module;
}
#endif

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: cppfort <source.cpp2> [output]\n";
        std::cerr << "  Default: parses cpp2 source and outputs canonical AST\n";
        std::cerr << "  With -c: outputs C++ code\n";
        std::cerr << "  With -o <file>: compiles to executable\n";
        std::cerr << "  Post-dogfood: will compile to MLIR SoN → LLVM\n";
        return 1;
    }
    
    // Parse arguments
    bool emit_cpp = false;
    bool compile_exe = false;
    std::string input_path;
    std::string output_path;
    
    int arg_idx = 1;
    while (arg_idx < argc) {
        std::string arg = argv[arg_idx];
        if (arg == "-c") {
            emit_cpp = true;
        } else if (arg == "-o") {
            if (arg_idx + 1 >= argc) {
                std::cerr << "Error: -o requires output file argument\n";
                return 1;
            }
            compile_exe = true;
            output_path = argv[arg_idx + 1];
            arg_idx++;
        } else if (arg[0] != '-') {
            input_path = arg;
        }
        arg_idx++;
    }
    
    if (input_path.empty()) {
        std::cerr << "Error: No input file specified\n";
        return 1;
    }
    
    std::ifstream input_file(input_path);
    
    if (!input_file.is_open()) {
        std::cerr << "Error: Cannot open input file: " << input_path << "\n";
        return 2;
    }
    
    std::stringstream source_stream;
    source_stream << input_file.rdbuf();
    std::string source = source_stream.str();
    input_file.close();
    
#ifdef CPPFORT_HAS_SON_DIALECT
    // Initialize MLIR context with cpp2 SoN dialect + arith
    mlir::MLIRContext context;
    context.getOrLoadDialect<cpp2::Cpp2SONDialect>();
    context.getOrLoadDialect<mlir::arith::ArithDialect>();
    std::cerr << "cppfort: SoN dialect loaded (cpp2 namespace)\n";
#endif

    std::cerr << "cppfort: parsing " << input_path << " (" << source.size() << " bytes)\n";
    auto ast_result = parse_source(std::string_view(source));

    if (!ast_result.has_value()) {
        std::cerr << "Error: Parse failed\n";
        return 3;
    }

    auto& ast = ast_result.value();
    std::cerr << "cppfort: parsed " << ast.size() << " canonical nodes\n";
    
    for (size_t i = 0; i < ast.size(); ++i) {
        const auto& node = ast[i];
        std::cerr << "  node[" << i << "]: tag=" << node.tag;
        std::cerr << " span=" << node.source_start << "-" << node.source_stop;
        if (!node.semantic.empty()) {
            std::cerr << " semantic=\"" << node.semantic << "\"";
        }
        std::cerr << "\n";
    }
    
#ifdef CPPFORT_HAS_SON_DIALECT
    // AST-to-MLIR: convert canonical AST to SoN dialect ops
    auto son_module = ast_to_son_module(context, ast, source);
    if (son_module) {
        std::cerr << "cppfort: SoN module verified (";
        std::cerr << son_module->getBody()->getOperations().size() << " top-level ops)\n";
        // Print module to stderr for verification
        son_module->dump();
    } else {
        std::cerr << "cppfort: SoN module creation failed\n";
    }
#endif

    // Emit C++ code from canonical AST using source text for accurate extraction
    std::string cpp_code = emit_cpp_from_ast(ast, source);
    
    if (emit_cpp) {
        // Output C++ code
        if (compile_exe) {
            std::ofstream out_file(output_path);
            if (!out_file.is_open()) {
                std::cerr << "Error: Cannot open output file: " << output_path << "\n";
                return 4;
            }
            out_file << cpp_code;
            out_file.close();
            std::cerr << "cppfort: wrote C++ to " << output_path << "\n";
        } else {
            std::cout << cpp_code;
        }
    } else if (compile_exe) {
        // Compile to executable
        std::string temp_cpp = "/tmp/cppfort_compile.cpp";
        std::ofstream cpp_file(temp_cpp);
        cpp_file << cpp_code;
        cpp_file.close();
        
        std::cerr << "cppfort: compiling to " << output_path << "\n";
        
        std::string compile_cmd = "clang++ -std=c++20 -o " + output_path + " " + temp_cpp + " 2>&1";
        int result = system(compile_cmd.c_str());
        
        if (result != 0) {
            std::cerr << "Error: Compilation failed with code " << result << "\n";
            return 5;
        }
        
        std::cerr << "cppfort: compiled executable to " << output_path << "\n";
    } else {
        // Default: output AST
        if (argc >= 3) {
            std::string output_path = argv[2];
            std::ofstream output_file(output_path);
            
            if (!output_file.is_open()) {
                std::cerr << "Error: Cannot open output file: " << output_path << "\n";
                return 4;
            }
            
            output_file << "// cppfort canonical AST output\n";
            output_file << "// Source: " << input_path << "\n";
            output_file << "// Nodes: " << ast.size() << "\n\n";
            
// Debug: dump features before returning
    std::cerr << "DEBUG: Dumping " << session.features.size() << " features:\n";
    for (const auto& feat : session.features) {
        std::cerr << "  feature: span=" << feat.start << "-" << feat.stop 
                  << " semantic=\"" << feat.semantic << "\"\n";
    }
    std::cerr << "DEBUG: Dumping " << ast.size() << " nodes:\n";
    for (size_t i = 0; i < ast.size(); ++i) {
                const auto& node = ast[i];
                output_file << "node[" << i << "]:\n";
                output_file << "  tag: " << node.tag << "\n";
                output_file << "  span: " << node.source_start << "-" << node.source_stop << "\n";
                output_file << "  semantic: \"" << node.semantic << "\"\n";
                output_file << "  children: " << node.children.size() << "\n\n";
            }
            
            output_file.close();
            std::cerr << "cppfort: wrote canonical AST to " << output_path << "\n";
        }
    }
    
    std::cerr << "cppfort: success\n";
    return 0;
}
