
#define CPP2_IMPORT_STD          Yes

//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

#line 1 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"


//=== Cpp2 type definitions and function declarations ===========================

#line 1 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
// canonical_emitter.cpp2 - Emit C++ code from canonical AST
// Minimal dogfood path: bypass MLIR for now, emit C++ directly like cppfront
// Post-dogfood: Replace with MLIR SoN lowering

#line 5 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
[[nodiscard]] auto emit_cpp_from_canonical(
    cpp2::impl::in<std::vector<canonical_node>> nodes, 
    std::string& output
) -> bool;

#line 65 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
auto emit_tag_declaration(cpp2::impl::in<std::string> semantic, std::string& output) -> void;

#line 104 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
[[nodiscard]] auto extract_tag_name(cpp2::impl::in<std::string> semantic) -> std::string;

//=== Cpp2 function definitions =================================================

#line 1 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"

#line 5 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
[[nodiscard]] auto emit_cpp_from_canonical(
    cpp2::impl::in<std::vector<canonical_node>> nodes, 
    std::string& output
) -> bool{
    output = "// Generated by cppfort from canonical AST\n";
    output += "// Minimal dogfood bootstrap\n\n";
    output += "#include <iostream>\n\n";

    bool has_tags {false}; 

    int i {0}; 
    int fsz {cpp2::unchecked_narrow<int>(CPP2_UFCS(size)(nodes))}; 
    while( cpp2::impl::cmp_less(i,fsz) ) {
        canonical_node node {CPP2_ASSERT_IN_BOUNDS(nodes, cpp2::unchecked_narrow<std::size_t>(i))}; 

        // Tag 21 = canonical_normalize_tag (bootstrap tag declarations)
        if (node.tag == 21) {
            emit_tag_declaration(cpp2::move(node).semantic, output);
            has_tags = true;
        }

        i += 1;
    }

    if (cpp2::move(has_tags)) {
        output += "\nint main() {\n";
        output += "    std::cout << \"cppfort bootstrap: \" << ";

        bool first {true}; 
        i = 0;
        while( cpp2::impl::cmp_less(i,fsz) ) {
            canonical_node node {CPP2_ASSERT_IN_BOUNDS(nodes, cpp2::unchecked_narrow<std::size_t>(i))}; 
            if (node.tag == 21) {
                std::string tag_name {extract_tag_name(cpp2::move(node).semantic)}; 
                if (!(CPP2_UFCS(empty)(tag_name))) {
                    if (!(first)) {
                        output += " << \", \" << ";
                    }
                    output += tag_name;
                    output += "=";
                    output += cpp2::move(tag_name);
                    first = false;
                }
            }
            i += 1;
        }

        output += " << \"\\n\";\n";
        output += "    return 0;\n";
        output += "}\n";
    }else {
        output += "\nint main() {\n";
        output += "    std::cout << \"cppfort: no tags found\\n\";\n";
        output += "    return 0;\n";
        output += "}\n";
    }

    return true; 
}

#line 65 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
auto emit_tag_declaration(cpp2::impl::in<std::string> semantic, std::string& output) -> void{
    std::size_t colon_pos {CPP2_UFCS(find)(semantic, ':')}; 
    std::size_t eq_pos {CPP2_UFCS(find)(semantic, '=')}; 

    if (colon_pos == std::string::npos || eq_pos == std::string::npos) {
        return ; 
    }

    std::string name {CPP2_UFCS(substr)(semantic, 0, colon_pos)}; 
    std::size_t name_start {CPP2_UFCS(find_first_not_of)(name, " \t")}; 
    std::size_t name_end {CPP2_UFCS(find_last_not_of)(name, " \t")}; 
    if (name_start != std::string::npos && name_end != std::string::npos) {
        name = CPP2_UFCS(substr)(name, name_start, cpp2::move(name_end) - name_start + 1);
    }

    std::size_t type_start {cpp2::move(colon_pos) + 1}; 
    std::size_t type_len {eq_pos - type_start}; 
    std::string ty {CPP2_UFCS(substr)(semantic, cpp2::move(type_start), cpp2::move(type_len))}; 
    std::size_t ty_start {CPP2_UFCS(find_first_not_of)(ty, " \t")}; 
    std::size_t ty_end {CPP2_UFCS(find_last_not_of)(ty, " \t")}; 
    if (ty_start != std::string::npos && ty_end != std::string::npos) {
        ty = CPP2_UFCS(substr)(ty, ty_start, cpp2::move(ty_end) - ty_start + 1);
    }

    std::size_t val_start {cpp2::move(eq_pos) + 1}; 
    std::string val {CPP2_UFCS(substr)(semantic, cpp2::move(val_start))}; 
    std::size_t val_start_idx {CPP2_UFCS(find_first_not_of)(val, " \t")}; 
    std::size_t val_end {CPP2_UFCS(find_last_not_of)(val, " \t;")}; 
    if (val_start_idx != std::string::npos && val_end != std::string::npos) {
        val = CPP2_UFCS(substr)(val, val_start_idx, cpp2::move(val_end) - val_start_idx + 1);
    }

    output += "constexpr int ";
    output += cpp2::move(name);
    output += " = ";
    output += cpp2::move(val);
    output += ";\n";
}

#line 104 "/Users/jim/work/cppfort/src/selfhost/canonical_emitter.cpp2"
[[nodiscard]] auto extract_tag_name(cpp2::impl::in<std::string> semantic) -> std::string{
    std::size_t colon_pos {CPP2_UFCS(find)(semantic, ':')}; 
    if (colon_pos == std::string::npos) {
        return ""; 
    }

    std::string name {CPP2_UFCS(substr)(semantic, 0, cpp2::move(colon_pos))}; 
    std::size_t start {CPP2_UFCS(find_first_not_of)(name, " \t")}; 
    std::size_t end {CPP2_UFCS(find_last_not_of)(name, " \t")}; 
    if (start != std::string::npos && end != std::string::npos) {
        name = CPP2_UFCS(substr)(name, start, cpp2::move(end) - start + 1);
    }

    return name; 
}

