// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

int main();
void hello_user(std::string_view name);

int main() {
    std::string greeting = "Hello, world!";
    std::string shout = greeting + "!!!";
    std::cout << greeting << "\n";
    std::cout << shout << "\n";
}

void hello_user(std::string_view name) {
    std::string message = std::string{"Hello, "} + std::string{name};
    std::cout << message << "\n";
}

