// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

int main();

int main() {
    int x = 1;
    int y = 2;
    int z = x & y;
    int w = x | y;
    int v = x ^ y;
    int u = x << 1;
    int t = y >> 1;
    return z + w + v + u + t;
}

