// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

using i8 = std::int8_t;
using i16 = std::int16_t;
using i32 = std::int32_t;
using i64 = std::int64_t;
using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u32 = std::uint32_t;
using u64 = std::uint64_t;

auto main() -> int /*kinds:*/{
    std::string s = "Fred";
    auto myfile = fopen("xyzzy", "w");
    fprintf(myfile, "Hello %s with UFCS!", s.c_str());
    fclose(myfile);
    return 0;
}
