// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

#include <iostream>
#include <string>

std::string name();
void decorate(std::string& s);
int main();

std::string name() {
    std::string s = "world";
    decorate(s);
    return s;
}

void decorate(std::string& s) {
    s = "[" + s + "]";
}

int main() {
    std::cout << "Hello " << name() << "\n";
}

