// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <vector>
#include <utility>
#include "cpp2.h"

using i8 = ::std::int8_t;
using i16 = ::std::int16_t;
using i32 = ::std::int32_t;
using i64 = ::std::int64_t;
using u8 = ::std::uint8_t;
using u16 = ::std::uint16_t;
using u32 = ::std::uint32_t;
using u64 = ::std::uint64_t;

// Forward declarations
auto main() -> int;
auto name() -> std::string;
auto decorate(std::string& s) -> void;


auto main() -> int /*kinds:*/{
    std::cout << "Hello " << name() << "\n";
    return 0;
}

auto name() -> std::string /*kinds:*/{
    std::string s = "world";
    decorate(s);
    return s;
}

auto decorate(std::string& s) -> void /*kinds:InOut*/{
    s = "[" + s + "]";
}
