// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>
#include <cstdint>
#include <compare>
#include <cpp2_runtime.h>

auto f(int const& a, auto const& b) -> void;

auto f(int const& a, auto const& b) -> void {
}

int main(int argc, char* argv[]) {
    auto args = cpp2::make_args(argc, argv);
}

