// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>
#include <cstdint>
#include <compare>
#include <cpp2_runtime.h>


int main(int argc, char* argv[]) {
    auto args = cpp2::make_args(argc, argv);
        auto s = R"($-[0])";
}

