// Generated by cppfort - slim ParseTree emitter
// Expected output for markdown_cas_empty.cpp2

#include <iostream>
#include <string>
#include <cstdint>
#include <compare>
#include <cpp2_runtime.h>

export module __cas_e3b0c44298fc1c14;
inline constexpr char cas_sha256[] = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

export module mymodule;
inline constexpr char cas_sha256[] = "64ec88ca00b268e5ba1a35678a1b5316d212f4f366b2477232534a8aeca37f3c";

auto main() -> int {
        return 0;
}
