// Generated by cppfort - slim ParseTree emitter
// Expected output for markdown_cas_bytespec.cpp2

#include <iostream>
#include <string>
#include <cstdint>
#include <compare>
#include <cpp2_runtime.h>

export module testmodule;
inline constexpr char cas_sha256[] = "a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e";

auto main() -> int {
        std::cout << "Test passed";
        return 0;
}
