// Generated by cppfort - slim ParseTree emitter
// Expected output for tailcall_fibonacci.cpp2

#include <iostream>
#include <string>
#include <cstdint>
#include <compare>
#include <cpp2_runtime.h>

auto fib(const int& n) -> int;
auto fib_tail_helper(const int& n, const int& acc, const int& prev) -> int;
auto fib_tail(const int& n) -> int;

auto fib(const int& n) -> int {
        if (n<=1) {
                return n;
    }
        return fib(n-1)+fib(n-2);
}

auto fib_tail_helper(const int& n, const int& acc, const int& prev) -> int {
        if (n==0) {
                return acc;
    }
        return fib_tail_helper(n-1,acc+prev,acc);
}

auto fib_tail(const int& n) -> int {
        return fib_tail_helper(n,1,0);
}

auto main() -> int {
        std::cout << "fib(10) = " << fib(10) << "\n";
        std::cout << "fib_tail(10) = " << fib_tail(10) << "\n";
        return 0;
}
