int main() { auto s1 = u"u\"";
    auto s2 = U"U\"";
    auto s3 = u8"u8\"";
    auto s4 = L"L\"";
    auto s5 = R"(R")";
    s6 := uR"(uR")";
    s7 := u8R"(u8R")";
    s8 := UR"(UR")";
    s9 := LR"(LR")";
    _ = s1;
    _ = s2;
    _ = s3;
    _ = s4;
    _ = s5;
    _ = s6;
    _ = s7;
    _ = s8;
    _ = s9; }
