// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>

int main(int argc, char* argv[]) {
        auto x ;
        _=x;
}

struct crash_m0 {
    // TODO: type body
};

