// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>

int main(int argc, char* argv[]) {
        auto s1 ;
        auto s2 ;
        auto s3 ;
        auto s4 ;
        auto s5 ;
        auto s6 ;
        auto s7 ;
        auto s8 ;
        auto s9 ;
        _=s1;
        _=s2;
        _=s3;
        _=s4;
        _=s5;
        _=s6;
        _=s7;
        _=s8;
        _=s9;
}

