// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>

auto f0() -> _ {
        return 42;
}

auto f1() -> _ {
        return f0;
}

auto f2() -> _ {
        return f1;
}

auto f3() -> _ {
        return f2;
}

auto f4() -> _ {
        return f3;
}

