// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>

auto fine() -> int {
        auto up ;
        auto sp ;
        auto op ;
        auto ex ;
        return up*+sp*+op*+ex*;
}

