// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>

int main(int argc, char* argv[]) {
        print_an_int("syzygy");
        print_an_int(1);
        print_an_int(1.1);
}

