// Generated by cppfort - slim ParseTree emitter
#include <iostream>
#include <string>

int main(int argc, char* argv[]) {
        auto s ;
        auto myfile ;
        _=myfile.fprintf("Hello %s with UFCS!",s.c_str());
        _=myfile.fclose();
}

