#!/bin/bash

# Script to run cppfront regression tests
# This file is generated by CMake - do not edit directly

set -e

# Default test directory
TEST_DIR="${TEST_DIR:-/tmp/cppfront-test/regression-tests}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if cppfort is available
if ! command -v cppfort &> /dev/null; then
    print_error "cppfort not found in PATH"
    print_error "Please ensure cppfort is built and installed"
    exit 1
fi

# Check if test directory exists
if [ ! -d "$TEST_DIR" ]; then
    print_error "Test directory not found: $TEST_DIR"
    print_error "Please ensure cppfront test files are available"
    exit 1
fi

# Print banner
print_status "Cppfront Regression Test Suite"
print_status "================================"
print_status "Test directory: $TEST_DIR"
print_status "Using cppfort: $(which cppfort)"

# Run the test executable
print_status "Running regression tests..."

if ./cppfront_full_regression --test-dir "$TEST_DIR" "$@"; then
    print_status "All regression tests completed successfully!"
    exit 0
else
    print_error "Some regression tests failed!"
    exit 1
fi
