// Generated by cppfort stage0 transpiler
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

auto main() -> void {
    std::string greeting = "Hello, world!";
    std::string shout = greeting + "!!!";
    std::cout << greeting << "\n";
    std::cout << shout << "\n";
}

auto hello_user(std::string_view name) -> void {
    std::string message = std::string{"Hello, "} + std::string{name};
    std::cout << message << "\n";
}
