// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

using i8 = ::std::int8_t;
using i16 = ::std::int16_t;
using i32 = ::std::int32_t;
using i64 = ::std::int64_t;
using u8 = ::std::uint8_t;
using u16 = ::std::uint16_t;
using u32 = ::std::uint32_t;
using u64 = ::std::uint64_t;

// Forward declarations
auto fine() -> int;
auto bad_shared_ptr_access() -> int;
auto main() -> int;


auto fine() -> int /*kinds:*/{
    auto up = ::std::make_unique<int>(1);
    auto sp = ::std::make_shared<int>(2);
    std::optional<int> op = 3;
    return *up + *sp + *op;
}

auto bad_shared_ptr_access() -> int /*kinds:*/{
    auto sp = std::make_shared<int>(1);
    sp.reset();
    return *sp;
}

auto main() -> int /*kinds:*/{
    std::set_terminate(std::abort);
    return fine() + bad_shared_ptr_access();
    return 0;
}
