// Generated by cppfort stage0 transpiler
#include <cstdint>
#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <vector>
#include <utility>
#include "cpp2.h"
#include <cassert>

using i8 = ::std::int8_t;
using i16 = ::std::int16_t;
using i32 = ::std::int32_t;
using i64 = ::std::int64_t;
using u8 = ::std::uint8_t;
using u16 = ::std::uint16_t;
using u32 = ::std::uint32_t;
using u64 = ::std::uint64_t;

// Forward declarations
auto crash_10(i32 foo) -> void;


auto crash_10(i32 foo) -> void /*kinds:Default*/{
    assert((cpp2::impl::as_<i32>(10LL) == foo$));
}
