# CMake generated Testfile for 
# Source directory: /Users/jim/work/cppfort/src/stage0
# Build directory: /Users/jim/work/cppfort/build_ninja_test/src/stage0
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_cpp2_cas]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_cpp2_cas")
set_tests_properties([=[test_cpp2_cas]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;277;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_cpp2_cas_golden]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_cpp2_cas_golden")
set_tests_properties([=[test_cpp2_cas_golden]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;292;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_graph_matcher_stub]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_graph_matcher_stub")
set_tests_properties([=[test_graph_matcher_stub]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;348;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_graph_matcher_with_pattern]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_graph_matcher_with_pattern")
set_tests_properties([=[test_graph_matcher_with_pattern]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;354;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_json_scanner_simple]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_json_scanner_simple")
set_tests_properties([=[test_json_scanner_simple]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;360;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_rbcursive_scanner_basic]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_rbcursive_scanner_basic")
set_tests_properties([=[test_rbcursive_scanner_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;389;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_orbit_pipeline_pattern_selection]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_orbit_pipeline_pattern_selection")
set_tests_properties([=[test_orbit_pipeline_pattern_selection]=] PROPERTIES  ENVIRONMENT "DEBUG_WATCHDOG_SECONDS=30" _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;390;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_base_orbit_graph_node_ownership]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_base_orbit_graph_node_ownership")
set_tests_properties([=[test_base_orbit_graph_node_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;396;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_populate_iterator_graph_node_set]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_populate_iterator_graph_node_set")
set_tests_properties([=[test_populate_iterator_graph_node_set]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;402;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_json_yaml_plasma_transpiler]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_json_yaml_plasma_transpiler")
set_tests_properties([=[test_json_yaml_plasma_transpiler]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;419;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_region_node_basic]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_region_node_basic")
set_tests_properties([=[test_region_node_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;420;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_region_node_ssa]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_region_node_ssa")
set_tests_properties([=[test_region_node_ssa]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;421;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[stage0_confix_cache]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_confix_cache")
set_tests_properties([=[stage0_confix_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;425;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[stage0_parameter_transform]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_parameter_transform")
set_tests_properties([=[stage0_parameter_transform]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;426;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[stage0_regression_suite]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/regression_runner" "/Users/jim/work/cppfort/tests/regression-tests" "/Users/jim/work/cppfort/patterns/bnfc_cpp2_complete.yaml" "/Users/jim/work/cppfort/build_ninja_test/src/stage0/stage0_cli")
set_tests_properties([=[stage0_regression_suite]=] PROPERTIES  TIMEOUT "300" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/jim/work/cppfort/tests/regression-tests" _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;427;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[stage0_regression_suite_git]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/regression_runner_git" "/Users/jim/work/cppfort" "/Users/jim/work/cppfort/patterns/bnfc_cpp2_complete.yaml" "/Users/jim/work/cppfort/build_ninja_test/src/stage0/stage0_cli" "--limit" "200")
set_tests_properties([=[stage0_regression_suite_git]=] PROPERTIES  TIMEOUT "1200" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/jim/work/cppfort/tests/regression-tests" _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;447;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
add_test([=[test_timeout_verification]=] "/Users/jim/work/cppfort/build_ninja_test/src/stage0/test_timeout_verification")
set_tests_properties([=[test_timeout_verification]=] PROPERTIES  TIMEOUT "3" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/jim/work/cppfort/build_ninja_test/src/stage0" _BACKTRACE_TRIPLES "/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;464;add_test;/Users/jim/work/cppfort/src/stage0/CMakeLists.txt;0;")
