#!/usr/bin/env python3
"""
BMAD Agent Executor - Execute agent tasks using GitHub Copilot API

Integrates with GitHub Copilot API to execute BMAD agent tasks autonomously.
"""
import argparse
import os
import sys
import json
import subprocess
from pathlib import Path
import requests

def execute_with_copilot_api(agent_type: str, prompt: str, repo_path: Path) -> dict:
    """Execute task using GitHub Copilot API"""
    api_key = os.environ.get('GITHUB_TOKEN')
    if not api_key:
        print("ERROR: GITHUB_TOKEN not set", file=sys.stderr)
        sys.exit(1)

    # Agent system prompts
    agent_prompts = {
        'dev': """You are a senior software engineer implementing features in a cpp2 transpiler.
Focus on correctness, testing, and clean code. You have access to the full repository context.
Make actual code changes, run tests, and verify your implementation works.""",
        'architect': """You are a system architect designing solutions for a cpp2 compiler.
Focus on patterns, scalability, and technical decisions. Design the solution and implement it.""",
        'qa': """You are a QA engineer testing a cpp2 transpiler.
Focus on test coverage, edge cases, and quality validation. Write and run tests.""",
        'analyst': """You are a technical analyst optimizing a cpp2 compiler.
Focus on performance, metrics, and optimization. Profile, measure, and improve.""",
        'sm': """You are a scrum master coordinating work on a cpp2 project.
Focus on process, workflow, and team coordination. Organize and document.""",
    }

    system_prompt = agent_prompts.get(agent_type, "You are a helpful coding assistant.")

    print(f"Executing {agent_type} agent via GitHub Copilot API...", file=sys.stderr)

    # Create message with full task context
    full_prompt = f"""You are working in repository: {repo_path}

{system_prompt}

{prompt}

**IMPORTANT INSTRUCTIONS:**
1. Read relevant files to understand the codebase
2. Make the necessary changes to implement the task
3. Run tests to validate your changes
4. Output a summary of what you did

You have full access to the repository. Make actual changes - this is not a simulation.
"""

    # GitHub Copilot Chat API endpoint
    url = "https://api.github.com/copilot/chat/completions"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    payload = {
        "messages": [
            {
                "role": "user",
                "content": full_prompt
            }
        ],
        "model": "gpt-4o",  # Copilot uses GPT-4o
        "max_tokens": 4096,
        "temperature": 0.1
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()

        data = response.json()
        content = data["choices"][0]["message"]["content"] if data.get("choices") else ""

        return {
            'success': True,
            'content': content,
            'usage': {
                'input_tokens': data.get('usage', {}).get('prompt_tokens', 0),
                'output_tokens': data.get('usage', {}).get('completion_tokens', 0)
            }
        }
    except requests.exceptions.RequestException as e:
        print(f"ERROR: GitHub Copilot API request failed: {e}", file=sys.stderr)
        return {
            'success': False,
            'content': f"API Error: {e}",
            'usage': {'input_tokens': 0, 'output_tokens': 0}
        }

def execute_with_local_commands(agent_type: str, prompt: str, repo_path: Path) -> dict:
    """Execute task using local shell commands (fallback)"""
    print(f"Executing {agent_type} agent via local commands...", file=sys.stderr)

    # Extract task list from prompt
    response = f"""# {agent_type.upper()} Agent Response

## Task Analysis

{prompt}

## Implementation Plan

Executed via local command fallback mode.

## Changes Made

No automated changes - manual implementation required.

## Next Steps

- Review the prompt above
- Execute tasks listed in acceptance criteria manually
- Commit changes when complete

---
Generated by BMAD executor (local fallback mode)
"""

    return {
        'success': True,
        'content': response,
        'usage': {'input_tokens': 0, 'output_tokens': 0}
    }

def main():
    parser = argparse.ArgumentParser(description='Execute BMAD agent task')
    parser.add_argument('--agent', required=True, help='Agent type (dev, architect, qa, etc.)')
    parser.add_argument('--prompt', required=True, help='Path to prompt file')
    parser.add_argument('--output', required=True, help='Path to output file')
    parser.add_argument('--mode', default='api', choices=['api', 'local'],
                       help='Execution mode: api (GitHub Copilot API) or local (fallback)')
    args = parser.parse_args()

    # Read prompt
    with open(args.prompt, 'r') as f:
        prompt = f.read()

    # Determine repo path (assume we're in repo root during CI)
    repo_path = Path(os.getcwd())

    # Execute based on mode
    if args.mode == 'api' and os.environ.get('GITHUB_TOKEN'):
        result = execute_with_copilot_api(args.agent, prompt, repo_path)
    else:
        if args.mode == 'api':
            print("WARNING: GITHUB_TOKEN not set, falling back to local mode", file=sys.stderr)
        result = execute_with_local_commands(args.agent, prompt, repo_path)

    # Write output
    with open(args.output, 'w') as f:
        f.write(result['content'])

    # Write metadata
    metadata_path = args.output + '.metadata.json'
    with open(metadata_path, 'w') as f:
        json.dump({
            'agent': args.agent,
            'mode': args.mode,
            'success': result['success'],
            'usage': result['usage']
        }, f, indent=2)

    print(f"Agent execution complete. Output: {args.output}", file=sys.stderr)
    if result['usage']['output_tokens'] > 0:
        print(f"Token usage: {result['usage']['input_tokens']} in, {result['usage']['output_tokens']} out", file=sys.stderr)

    sys.exit(0 if result['success'] else 1)

if __name__ == '__main__':
    main()
