#include "emitter.hpp"
#include <iostream>
#include <sstream>
#include <vector>
#include <cctype>

namespace {

using namespace cpp2::ast;

class TreeEmitter {
    const ParseTree& tree_;
    std::span<const cpp2_transpiler::Token> tokens_;
    std::ostringstream out_;
    int indent_ = 0;

    void emit_indent() {
        for (int i = 0; i < indent_; ++i) out_ << "    ";
    }

    std::string_view token_text(uint32_t idx) const {
        if (idx < tokens_.size()) return tokens_[idx].lexeme;
        return "";
    }

    std::string node_text(const Node& n) const {
        std::string result;
        for (uint32_t i = n.token_start; i < n.token_end && i < tokens_.size(); ++i) {
            if (!result.empty() && !tokens_[i].lexeme.empty()) {
                char prev = result.back();
                char next = tokens_[i].lexeme[0];
                if (std::isalnum(prev) && std::isalnum(next)) result += ' ';
            }
            result += tokens_[i].lexeme;
        }
        return result;
    }

public:
    TreeEmitter(const ParseTree& tree, std::span<const cpp2_transpiler::Token> tokens)
        : tree_(tree), tokens_(tokens) {}

    std::string emit() {
        out_ << "// Generated by cppfort - slim ParseTree emitter\n";
        out_ << "#include <iostream>\n";
        out_ << "#include <string>\n\n";

        if (tree_.nodes.empty()) return out_.str();

        const auto& root = tree_[tree_.root];
        for (const auto& child : tree_.children(root)) {
            emit_declaration(child);
        }

        return out_.str();
    }

private:
    void emit_declaration(const Node& n) {
        if (n.kind != NodeKind::Declaration) return;

        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::UnifiedDeclaration) {
                emit_unified_decl(child);
            }
        }
    }

    void emit_unified_decl(const Node& n) {
        // Extract name from first token
        std::string name = std::string(token_text(n.token_start));

        // Check for function suffix vs variable suffix
        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::FunctionSuffix) {
                emit_function(name, child);
                return;
            }
            if (child.kind == NodeKind::VariableSuffix) {
                emit_variable(name, child);
                return;
            }
            if (child.kind == NodeKind::TypeSuffix) {
                emit_type(name, child);
                return;
            }
            if (child.kind == NodeKind::NamespaceSuffix) {
                emit_namespace(name, child);
                return;
            }
        }

        // Fallback: simple variable with := initialization
        emit_indent();
        // Check if we have an expression child for initialization
        std::string init;
        for (const auto& child : tree_.children(n)) {
             if (meta::is_expression(child.kind) || child.kind == NodeKind::AssignmentExpression) {
                 init = node_text(child);
                 break;
             }
        }
        
        if (!init.empty()) {
            out_ << "auto " << name << " = " << init << ";\n";
        } else {
             out_ << "auto " << name << "; // TODO: Unknown decl\n";
        }
    }

    void emit_function(const std::string& name, const Node& suffix) {
        // Extract return type (if any) and parameters
        std::string return_type = "auto";
        std::string params;
        const Node* body = nullptr;

        for (const auto& child : tree_.children(suffix)) {
            if (child.kind == NodeKind::ParamList) {
                params = emit_params(child);
            } else if (child.kind == NodeKind::ReturnSpec) {
                return_type = emit_type_spec(child);
            } else if (child.kind == NodeKind::FunctionBody) {
                body = &child;
            }
        }

        // Handle main function specially
        if (name == "main") {
            out_ << "int main(int argc, char* argv[]) {\n";
        } else {
            out_ << "auto " << name << "(" << params << ") -> " << return_type << " {\n";
        }

        ++indent_;
        if (body) emit_function_body(*body);
        --indent_;

        out_ << "}\n\n";
    }

    std::string emit_params(const Node& n) {
        std::string result;
        for (const auto& param : tree_.children(n)) {
            if (param.kind == NodeKind::Parameter) {
                if (!result.empty()) result += ", ";
                result += emit_param(param);
            }
        }
        return result;
    }

    std::string emit_param(const Node& n) {
        // Get param name and optional type
        std::string name;
        std::string type = "auto";
        std::string qualifier;  // inout, out, in, etc.

        // Check children for qualifier and type
        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::ParamQualifier) {
                qualifier = node_text(child);
            } else if (child.kind == NodeKind::Identifier) {
                name = node_text(child);
            } else if (child.kind == NodeKind::TypeSpecifier || child.kind == NodeKind::BasicType) {
                type = node_text(child);
            }
        }
        
        if (name.empty()) {
            // Fallback for cases where identifier might not be wrapped (legacy or specific patterns)
            // But be careful not to pick up qualifier if it exists
            if (!qualifier.empty()) {
                // If we have qualifier, token_start is qualifier. name must be later.
                // We should rely on children. If identifier node is missing, maybe it's implicit or failed parse?
                // Assuming parser always produces Identifier node for name now.
                // If fallback needed, maybe skip qualifier tokens?
                // For now, trust Identifier node.
            } else {
                 name = std::string(token_text(n.token_start));
            }
        }

        // Apply qualifiers to type
        std::string result_type = type;
        if (!qualifier.empty()) {
            if (qualifier == "inout" || qualifier == "out") {
                // Reference parameter
                if (type == "auto") {
                    result_type = "auto&";
                } else {
                    result_type = type + "&";
                }
            } else if (qualifier == "move") {
                // Rvalue reference
                if (type == "auto") {
                    result_type = "auto&&";
                } else {
                    result_type = type + "&&";
                }
            } else if (qualifier == "forward") {
                // Forwarding reference
                if (type == "auto") {
                    result_type = "auto&&";
                } else {
                    result_type = type + "&&";
                }
            } else if (qualifier == "in") {
                 // Const reference
                if (type == "auto") {
                    result_type = "const auto&";
                } else {
                    result_type = "const " + type + "&";
                }
            }
            // "copy" (value) is default, no change needed
        }

        return result_type + " " + name;
    }

    std::string emit_type_spec(const Node& n) {
        // Return spec has arrow -> type
        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::TypeSpecifier || child.kind == NodeKind::BasicType) {
                return node_text(child);
            }
        }
        // Fallback: get text after ->
        std::string text = node_text(n);
        auto pos = text.find("->");
        if (pos != std::string::npos) {
            std::string result = text.substr(pos + 2);
            // Trim whitespace
            while (!result.empty() && std::isspace(result.front())) result.erase(0, 1);
            return result.empty() ? "auto" : result;
        }
        return "auto";
    }

    void emit_function_body(const Node& n) {
        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::BlockStatement) {
                emit_block(child);
            } else {
                // Expression body: = expr;
                emit_indent();
                out_ << "return " << node_text(child) << ";\n";
            }
        }
    }

    void emit_block(const Node& n) {
        for (const auto& child : tree_.children(n)) {
            emit_statement(child);
        }
    }

    void emit_statement(const Node& n) {
        emit_indent();

        if (n.kind == NodeKind::ReturnStatement) {
            out_ << "return";
            for (const auto& child : tree_.children(n)) {
                out_ << " " << node_text(child);
            }
            out_ << ";\n";
        } else if (n.kind == NodeKind::IfStatement) {
            emit_if(n);
        } else if (n.kind == NodeKind::WhileStatement) {
            emit_while(n);
        } else if (n.kind == NodeKind::ForStatement) {
            emit_for(n);
        } else if (n.kind == NodeKind::BlockStatement) {
            out_ << "{\n";
            ++indent_;
            emit_block(n);
            --indent_;
            emit_indent();
            out_ << "}\n";
        } else if (n.kind == NodeKind::ExpressionStatement) {
            // Remove trailing semicolon if present in node_text to avoid double semicolon
            // Actually, we should call emit_expression for consistency
            // But node_text might include the semicolon if it was parsed as ExpressionStatement
            // Let's rely on emit_expression + ";"
            for (const auto& child : tree_.children(n)) {
                if (meta::is_expression(child.kind)) {
                    emit_expression(child);
                    out_ << ";\n";
                    return;
                }
            }
            // Fallback
             out_ << node_text(n) << "\n";
        } else if (n.kind == NodeKind::Statement) {
            // Generic statement - check children
            for (const auto& child : tree_.children(n)) {
                emit_statement(child);
            }
        } else if (n.kind == NodeKind::UnifiedDeclaration) {
            // Local variable
            emit_local_var(n);
        } else {
            out_ << node_text(n) << ";\n";
        }
    }

    void emit_if(const Node& n) {
        out_ << "if (";
        bool first = true;
        for (const auto& child : tree_.children(n)) {
            if (first && child.kind != NodeKind::BlockStatement && child.kind != NodeKind::Statement) {
                out_ << node_text(child);
                first = false;
            } else if (child.kind == NodeKind::BlockStatement) {
                out_ << ") {\n";
                ++indent_;
                emit_block(child);
                --indent_;
                emit_indent();
                out_ << "}";
            }
        }
        out_ << "\n";
    }

    void emit_while(const Node& n) {
        out_ << "while (";
        bool first = true;
        for (const auto& child : tree_.children(n)) {
            if (first && child.kind != NodeKind::BlockStatement) {
                out_ << node_text(child);
                first = false;
            } else if (child.kind == NodeKind::BlockStatement) {
                out_ << ") {\n";
                ++indent_;
                emit_block(child);
                --indent_;
                emit_indent();
                out_ << "} \n";
            }
        }
    }

    void emit_for(const Node& n) {
        // Cpp2 for: for items do (item) { body }
        // Emit as: for (auto item : items) { body }
        std::string items, var;
        const Node* body = nullptr;

        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::BlockStatement) {
                body = &child;
            } else if (child.kind == NodeKind::Identifier || 
                       (child.kind == NodeKind::Parameter && var.empty())) {
                var = node_text(child);
            } else if (items.empty() && child.kind != NodeKind::BlockStatement) {
                items = node_text(child);
            }
        }

        out_ << "for (auto " << var << " : " << items << ") {\n";
        ++indent_;
        if (body) emit_block(*body);
        --indent_;
        emit_indent();
        out_ << "}\n";
    }

    void emit_local_var(const Node& n) {
        std::string name = std::string(token_text(n.token_start));
        std::string type = "auto";
        const Node* init_expr = nullptr;

        // Check for children
        for (const auto& child : tree_.children(n)) {
            if (child.kind == NodeKind::VariableSuffix) {
                // Inside VariableSuffix: [TypeSpecifier] [= Expression] ;
                for (const auto& grandchild : tree_.children(child)) {
                    if (grandchild.kind == NodeKind::TypeSpecifier || grandchild.kind == NodeKind::BasicType) {
                        type = node_text(grandchild);
                    } else if (meta::is_expression(grandchild.kind)) {
                        init_expr = &grandchild;
                    }
                }
            } else if (child.kind == NodeKind::TypeSpecifier || child.kind == NodeKind::BasicType) {
                // Handle direct type specifier (parser quirk/bug workaround)
                type = node_text(child);
            } else if (meta::is_expression(child.kind)) {
                // Direct expression child means := deduction
                init_expr = &child;
            }
        }

        out_ << type << " " << name;
        if (init_expr) {
            out_ << " = ";
            emit_expression(*init_expr);
        }
        out_ << ";\n";
    }

    void emit_variable(const std::string& name, const Node& suffix) {
        // Global variable (from emit_unified_decl)
        emit_indent();
        
        std::string type = "auto";
        const Node* init_expr = nullptr;
        
        // Suffix might be VariableSuffix, or UnifiedDeclaration logic might have passed the suffix node
        // But emit_unified_decl passes the child node.
        
        // If suffix is VariableSuffix:
        if (suffix.kind == NodeKind::VariableSuffix) {
             for (const auto& child : tree_.children(suffix)) {
                 if (child.kind == NodeKind::TypeSpecifier || child.kind == NodeKind::BasicType) {
                    type = node_text(child);
                } else if (meta::is_expression(child.kind)) {
                    init_expr = &child;
                }
            }
        } else {
            // Check direct children of the suffix node (whatever it is)
             for (const auto& child : tree_.children(suffix)) {
                 if (child.kind == NodeKind::TypeSpecifier || child.kind == NodeKind::BasicType) {
                    type = node_text(child);
                } else if (meta::is_expression(child.kind)) {
                    init_expr = &child;
                }
            }
        }
        
        out_ << type << " " << name;
        if (init_expr) {
             out_ << " = ";
             emit_expression(*init_expr);
        }
        out_ << ";\n";
    }

    void emit_type(const std::string& name, const Node& /*suffix*/) {
        out_ << "struct " << name << " {\n";
        out_ << "    // TODO: type body\n";
        out_ << "};\n\n";
    }

    bool is_infix_expression(NodeKind k) const {
        using K = NodeKind;
        if (k < K::MultiplicativeExpression || k > K::AssignmentExpression) return false;
        return k != K::TernaryExpression && 
               k != K::PipelineExpression && 
               k != K::RangeExpression && 
               k != K::AssignmentOp;
    }

    void emit_expression(const Node& n) {
        if (n.kind == NodeKind::Literal || n.kind == NodeKind::Identifier) {
            out_ << node_text(n);
        } else if (n.kind == NodeKind::Expression) {
            for (const auto& child : tree_.children(n)) {
                emit_expression(child);
            }
        } else if (is_infix_expression(n.kind)) {
            bool first = true;
            for (const auto& child : tree_.children(n)) {
                if (child.kind == NodeKind::BinaryOp || 
                    child.kind == NodeKind::AssignmentOp || 
                    (child.token_start < child.token_end && is_operator(token_text(child.token_start)))) {
                    
                    out_ << " " << node_text(child) << " ";
                } else {
                    emit_expression(child);
                }
            }

        } else if (n.kind == NodeKind::CallOp) { // If we are recursing or node kind is CallOp
             out_ << "(";
             bool first = true;
             for (const auto& child : tree_.children(n)) {
                 if (!first) out_ << ", ";
                 emit_expression(child);
                 first = false;
             }
             out_ << ")";
        } else if (n.kind == NodeKind::MemberOp) {
            out_ << node_text(n);
        } else if (n.kind == NodeKind::SubscriptOp) {
            out_ << "[";
            for (const auto& child : tree_.children(n)) {
                emit_expression(child);
            }
            out_ << "]";
        } else if (n.kind == NodeKind::TernaryExpression) {
             out_ << " ? ";
             int i = 0;
             for (const auto& child : tree_.children(n)) {
                 if (i == 1) out_ << " : ";
                 emit_expression(child);
                 i++;
             }
        } else if (n.kind == NodeKind::GroupedExpression) {
             out_ << "(";
             for (const auto& child : tree_.children(n)) {
                 emit_expression(child);
             }
             out_ << ")";
        } else if (n.kind == NodeKind::PrefixExpression) {
             for (const auto& child : tree_.children(n)) {
                if (child.kind == NodeKind::PrefixOp) {
                    out_ << node_text(child);
                } else {
                    emit_expression(child);
                }
            }
        } else {
             // Fallback
             out_ << node_text(n);
        }
    }

    bool is_operator(std::string_view s) const {
        return s.find_first_not_of("+-*/%&|^<>=!~") == std::string_view::npos || s == "and" || s == "or" || s == "not";
    }

    void emit_namespace(const std::string& name, const Node& suffix) {
        out_ << "namespace " << name << " {\n\n";
        for (const auto& child : tree_.children(suffix)) {
            if (child.kind == NodeKind::NamespaceBody) {
                for (const auto& decl : tree_.children(child)) {
                    emit_declaration(decl);
                }
            }
        }
        out_ << "} // namespace " << name << "\n\n";
    }
};

} // anonymous namespace

std::string generate_from_tree(const cpp2::ast::ParseTree& tree,
                               std::span<const cpp2_transpiler::Token> tokens) {
    TreeEmitter emitter(tree, tokens);
    return emitter.emit();
}
