#include "emitter.hpp"
#include <cctype>
#include <iostream>
#include <sstream>
#include <vector>

namespace {

using namespace cpp2::ast;

class TreeEmitter {
  const ParseTree &tree_;
  std::span<const cpp2_transpiler::Token> tokens_;
  std::ostringstream out_;
  int indent_ = 0;

  void emit_indent() {
    for (int i = 0; i < indent_; ++i)
      out_ << "    ";
  }

  std::string_view token_text(uint32_t idx) const {
    if (idx < tokens_.size())
      return tokens_[idx].lexeme;
    return "";
  }

  // Check if a node's token range contains a specific token text
  bool node_contains_token(const Node &n, std::string_view target) const {
    for (uint32_t i = n.token_start; i < n.token_end && i < tokens_.size(); ++i) {
      if (tokens_[i].lexeme == target)
        return true;
    }
    return false;
  }

  std::string node_text(const Node &n) const {
    std::string result;
    for (uint32_t i = n.token_start; i < n.token_end && i < tokens_.size();
         ++i) {
      if (!result.empty() && !tokens_[i].lexeme.empty()) {
        char prev = result.back();
        char next = tokens_[i].lexeme[0];
        if (std::isalnum(prev) && std::isalnum(next))
          result += ' ';
      }
      result += tokens_[i].lexeme;
    }
    return result;
  }

  std::string map_type_name(const std::string &name) const {
    if (name == "i32")
      return "int";
    if (name == "u32")
      return "unsigned int";
    if (name == "i16")
      return "int16_t";
    if (name == "u16")
      return "uint16_t";
    if (name == "i8")
      return "int8_t";
    if (name == "u8")
      return "uint8_t";
    if (name == "i64")
      return "int64_t";
    if (name == "u64")
      return "uint64_t";
    if (name == "f32")
      return "float";
    if (name == "f64")
      return "double";
    return name;
  }

  std::string trim(std::string_view s) const {
    size_t first = s.find_first_not_of(" \t\n\r");
    if (first == std::string::npos)
      return "";
    size_t last = s.find_last_not_of(" \t\n\r");
    return std::string(s.substr(first, last - first + 1));
  }

  // Check if a function body contains a return statement with a value
  bool function_has_return_value(const Node &suffix) const {
    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::FunctionBody) {
        return body_has_return_value(child);
      }
    }
    return false;
  }

  bool body_has_return_value(const Node &n) const {
    // Check if any token in the body is a 'return' followed by something other than ';'
    for (uint32_t i = n.token_start; i < n.token_end && i < tokens_.size(); ++i) {
      if (tokens_[i].lexeme == "return") {
        // Check if there's a value after return (not just "return;")
        if (i + 1 < n.token_end && i + 1 < tokens_.size()) {
          if (tokens_[i + 1].lexeme != ";") {
            return true;  // Has a return value
          }
        }
      }
    }
    return false;  // No return with value found -> returns void
  }

  std::string format_type(const Node &n) const {
    std::string text = trim(node_text(n));
    // Simple heuristic: move leading * and & to the end
    size_t i = 0;
    std::string qualifiers;
    while (i < text.length() && (text[i] == '*' || text[i] == '&')) {
      qualifiers += text[i];
      i++;
    }
    std::string base = trim(text.substr(i));
    return map_type_name(base) + qualifiers;
  }

public:
  TreeEmitter(const ParseTree &tree,
              std::span<const cpp2_transpiler::Token> tokens)
      : tree_(tree), tokens_(tokens) {}

  std::string emit() {
    out_ << "// Generated by cppfort - slim ParseTree emitter\n";
    out_ << "#include <iostream>\n";
    out_ << "#include <string>\n";
    out_ << "#include <cstdint>\n";
    out_ << "#include <cpp2_runtime.h>\n\n";

    if (tree_.nodes.empty())
      return out_.str();

    const auto &root = tree_[tree_.root];
    
    // First pass: emit forward declarations for functions and types
    for (const auto &child : tree_.children(root)) {
      emit_forward_declaration(child);
    }
    out_ << "\n";
    
    // Second pass: emit type definitions (before functions that use them)
    for (const auto &child : tree_.children(root)) {
      emit_type_definition(child);
    }
    
    // Third pass: emit function definitions and other declarations
    for (const auto &child : tree_.children(root)) {
      emit_non_type_declaration(child);
    }

    return out_.str();
  }

private:
  // Check if a declaration is a type definition
  bool is_type_declaration(const Node &n) const {
    if (n.kind != NodeKind::Declaration)
      return false;
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::UnifiedDeclaration) {
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::TypeSuffix)
            return true;
        }
      }
    }
    return false;
  }

  // Emit only type definitions
  void emit_type_definition(const Node &n) {
    if (!is_type_declaration(n))
      return;
    emit_declaration(n);
  }

  // Emit declarations that are NOT type definitions
  void emit_non_type_declaration(const Node &n) {
    if (is_type_declaration(n))
      return;
    emit_declaration(n);
  }

  // Emit forward declaration for a function (just the signature, no body)
  void emit_forward_declaration(const Node &n) {
    if (n.kind != NodeKind::Declaration)
      return;

    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::UnifiedDeclaration) {
        emit_forward_unified_decl(child);
      }
    }
  }
  
  void emit_forward_unified_decl(const Node &n) {
    std::string name;
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
        break;
      }
    }
    if (name.empty()) {
      name = std::string(token_text(n.token_start));
    }

    // Check for type suffix (struct/class forward declaration)
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::TypeSuffix) {
        // Emit forward declaration for the type
        out_ << "class " << name << ";\n";
        return;
      }
    }

    // Check for function suffix (function forward declaration)
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::FunctionSuffix) {
        emit_function_forward(name, child);
        return;
      }
    }
  }
  
  void emit_function_forward(const std::string &name, const Node &suffix) {
    // Skip main function (doesn't need forward decl)
    if (name == "main")
      return;
      
    std::string return_type = "auto";
    std::string params;

    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::ParamList) {
        params = emit_params(child);
      } else if (child.kind == NodeKind::ReturnSpec) {
        return_type = emit_type_spec(child);
      }
    }

    // Check for named return type like (i:int)
    std::string named_return_type = extract_named_return_type(return_type);
    if (!named_return_type.empty()) {
      // Emit type alias: using funcname_ret = type;
      out_ << "using " << name << "_ret = " << named_return_type << ";\n";
      return_type = name + "_ret";
    }

    // For deduced return types, check if function returns void (no return value)
    // C++ allows forward-declaring void functions even without explicit return type
    if (return_type == "auto") {
      if (!function_has_return_value(suffix)) {
        return_type = "void";
      } else {
        // Has a return value but type is deduced - can't forward declare in C++
        return;
      }
    }

    out_ << "auto " << name << "(" << params << ") -> " << return_type << ";\n";
  }

  void emit_declaration(const Node &n) {
    if (n.kind != NodeKind::Declaration)
      return;

    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::UnifiedDeclaration) {
        emit_unified_decl(child);
      } else if (child.kind == NodeKind::FunctionSuffix) {
        // C++1 function declaration: auto name() -> type { body }
        // Find the identifier name from inside the FunctionSuffix
        std::string name = "unknown";
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::Identifier) {
            name = node_text(grandchild);
            break;
          }
        }
        emit_function(name, child);
      }
    }
  }

  void emit_unified_decl(const Node &n) {
    // Try to find identifier name from children first (for C++1 functions)
    std::string name;
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
        break;
      }
    }
    // Fallback to first token for Cpp2 declarations
    if (name.empty()) {
      name = std::string(token_text(n.token_start));
    }

    // Check for function suffix vs variable suffix
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::FunctionSuffix) {
        emit_function(name, child);
        return;
      }
      if (child.kind == NodeKind::VariableSuffix) {
        emit_variable(name, child);
        return;
      }
      if (child.kind == NodeKind::TypeSuffix) {
        emit_type(name, child);
        return;
      }
      if (child.kind == NodeKind::NamespaceSuffix) {
        emit_namespace(name, child);
        return;
      }
    }

    // Fallback: simple variable with := initialization
    emit_indent();
    // Check if we have an expression child for initialization
    std::string init;
    for (const auto &child : tree_.children(n)) {
      if (meta::is_expression(child.kind) ||
          child.kind == NodeKind::AssignmentExpression) {
        init = node_text(child);
        break;
      }
    }

    if (!init.empty()) {
      out_ << "auto " << name << " = " << init << ";\n";
    } else {
      out_ << "auto " << name << "; // TODO: Unknown decl\n";
    }
  }

  void emit_function(const std::string &name, const Node &suffix) {
    // Extract return type (if any) and parameters
    std::string return_type = "auto";
    std::string params;
    const Node *body = nullptr;

    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::ParamList) {
        params = emit_params(child);
      } else if (child.kind == NodeKind::ReturnSpec) {
        return_type = emit_type_spec(child);
      } else if (child.kind == NodeKind::FunctionBody) {
        body = &child;
      }
    }

    // Check for named return type like (i:int) - extract both name and type
    auto [named_ret_var, named_ret_type] = extract_named_return_info(return_type);
    if (!named_ret_type.empty()) {
      return_type = name + "_ret";
    }

    // Infer void return type when there's no explicit return type and no return value
    if (return_type == "auto" && !function_has_return_value(suffix)) {
      return_type = "void";
    }

    // Handle main function specially (only for Cpp2 syntax without explicit
    // return)
    if (name == "main" && return_type == "auto") {
      out_ << "int main(int argc, char* argv[]) {\n";
    } else {
      out_ << "auto " << name << "(" << params << ") -> " << return_type
           << " {\n";
    }

    ++indent_;
    if (body)
      emit_function_body(*body, named_ret_var, named_ret_type);
    --indent_;

    out_ << "}\n\n";
  }

  std::string emit_params(const Node &n) {
    std::string result;
    for (const auto &param : tree_.children(n)) {
      if (param.kind == NodeKind::Parameter) {
        if (!result.empty())
          result += ", ";
        result += emit_param(param);
      }
    }
    return result;
  }

  std::string emit_param(const Node &n) {
    // Get param name and optional type and default value
    std::string name;
    std::string type = "auto";
    std::string qualifier;     // inout, out, in, etc.
    std::string default_value; // Default argument value

    // Check children for qualifier, type, and default value
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::ParamQualifier) {
        qualifier = node_text(child);
      } else if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
      } else if (child.kind == NodeKind::TypeSpecifier ||
                 child.kind == NodeKind::BasicType) {
        type = format_type(child);
      } else if (meta::is_expression(child.kind)) {
        // This is the default value expression
        default_value = node_text(child);
      }
    }

    if (name.empty()) {
      // Fallback for cases where identifier might not be wrapped (legacy or
      // specific patterns) But be careful not to pick up qualifier if it exists
      if (!qualifier.empty()) {
        // If we have qualifier, token_start is qualifier. name must be later.
        // We should rely on children. If identifier node is missing, maybe it's
        // implicit or failed parse? Assuming parser always produces Identifier
        // node for name now. If fallback needed, maybe skip qualifier tokens?
        // For now, trust Identifier node.
      } else {
        name = std::string(token_text(n.token_start));
      }
    }

    // Apply qualifiers to type
    std::string result_type = type;
    if (!qualifier.empty()) {
      if (qualifier == "inout" || qualifier == "out") {
        // Reference parameter
        if (type == "auto") {
          result_type = "auto&";
        } else {
          result_type = type + "&";
        }
      } else if (qualifier == "move") {
        // Rvalue reference
        if (type == "auto") {
          result_type = "auto&&";
        } else {
          result_type = type + "&&";
        }
      } else if (qualifier == "forward") {
        // Forwarding reference
        if (type == "auto") {
          result_type = "auto&&";
        } else {
          result_type = type + "&&";
        }
      } else if (qualifier == "in") {
        // Const reference
        if (type == "auto") {
          result_type = "const auto&";
        } else {
          result_type = "const " + type + "&";
        }
      }
      // "copy" (value) is default, no change needed
    }

    std::string result = result_type + " " + name;
    if (!default_value.empty()) {
      result += " = " + default_value;
    }
    return result;
  }

  std::string emit_type_spec(const Node &n) {
    // Return spec has arrow -> type
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::TypeSpecifier ||
          child.kind == NodeKind::BasicType) {
        return format_type(child);
      }
    }
    // Fallback: get text after ->
    std::string text = node_text(n);
    auto pos = text.find("->");
    if (pos != std::string::npos) {
      std::string result = text.substr(pos + 2);
      // Trim whitespace
      while (!result.empty() && std::isspace(result.front()))
        result.erase(0, 1);
      return result.empty() ? "auto" : result;
    }
    return "auto";
  }
  
  // Check if return type is a named return like (i:int) and extract the type
  // Returns empty string if not a named return
  std::string extract_named_return_type(const std::string &return_spec) {
    // Pattern: (name:type) or ( name : type )
    std::string s = return_spec;
    // Trim whitespace
    while (!s.empty() && std::isspace(s.front())) s.erase(0, 1);
    while (!s.empty() && std::isspace(s.back())) s.pop_back();
    
    if (s.empty() || s.front() != '(' || s.back() != ')') 
      return "";
    
    // Remove outer parens
    s = s.substr(1, s.length() - 2);
    
    // Find the colon
    auto colon_pos = s.find(':');
    if (colon_pos == std::string::npos)
      return "";
    
    // Extract type after colon
    std::string type_part = s.substr(colon_pos + 1);
    // Trim whitespace
    while (!type_part.empty() && std::isspace(type_part.front())) 
      type_part.erase(0, 1);
    
    return type_part.empty() ? "" : type_part;
  }

  // Extract both name and type from named return like (i:int)
  // Returns {name, type} pair, or {"", ""} if not a named return
  std::pair<std::string, std::string> extract_named_return_info(const std::string &return_spec) {
    std::string s = return_spec;
    // Trim whitespace
    while (!s.empty() && std::isspace(s.front())) s.erase(0, 1);
    while (!s.empty() && std::isspace(s.back())) s.pop_back();
    
    if (s.empty() || s.front() != '(' || s.back() != ')') 
      return {"", ""};
    
    // Remove outer parens
    s = s.substr(1, s.length() - 2);
    
    // Find the colon
    auto colon_pos = s.find(':');
    if (colon_pos == std::string::npos)
      return {"", ""};
    
    // Extract name before colon
    std::string name_part = s.substr(0, colon_pos);
    // Trim whitespace
    while (!name_part.empty() && std::isspace(name_part.front())) 
      name_part.erase(0, 1);
    while (!name_part.empty() && std::isspace(name_part.back())) 
      name_part.pop_back();
    
    // Extract type after colon
    std::string type_part = s.substr(colon_pos + 1);
    // Trim whitespace
    while (!type_part.empty() && std::isspace(type_part.front())) 
      type_part.erase(0, 1);
    
    if (name_part.empty() || type_part.empty())
      return {"", ""};
    
    return {name_part, type_part};
  }

  void emit_function_body(const Node &n, const std::string &named_ret_var = "", const std::string &named_ret_type = "") {
    // If we have a named return variable, declare it at the top
    if (!named_ret_var.empty() && !named_ret_type.empty()) {
      emit_indent();
      out_ << named_ret_type << " " << named_ret_var << ";\n";
    }
    
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::BlockStatement) {
        emit_block(child, named_ret_var);
      } else {
        // Expression body: = expr;
        emit_indent();
        out_ << "return " << node_text(child) << ";\n";
      }
    }
    
    // If we have a named return variable and no explicit return at end, add one
    if (!named_ret_var.empty()) {
      // Check if the last statement was a return
      // For now, always emit return at end for named returns
      // (cppfront uses std::move on the return variable)
      // Note: this might duplicate return, but is safe
    }
  }

  void emit_block(const Node &n, const std::string &named_ret_var = "") {
    for (const auto &child : tree_.children(n)) {
      emit_statement(child, named_ret_var);
    }
  }

  void emit_statement(const Node &n, const std::string &named_ret_var = "") {
    emit_indent();

    if (n.kind == NodeKind::ReturnStatement) {
      out_ << "return";
      bool has_value = false;
      for (const auto &child : tree_.children(n)) {
        out_ << " " << node_text(child);
        has_value = true;
      }
      // If we have a named return var and no explicit return value, return the var
      if (!has_value && !named_ret_var.empty()) {
        out_ << " " << named_ret_var;
      }
      out_ << ";\n";
    } else if (n.kind == NodeKind::IfStatement) {
      emit_if(n, named_ret_var);
    } else if (n.kind == NodeKind::WhileStatement) {
      emit_while(n, named_ret_var);
    } else if (n.kind == NodeKind::ForStatement) {
      emit_for(n, named_ret_var);
    } else if (n.kind == NodeKind::BlockStatement) {
      out_ << "{\n";
      ++indent_;
      emit_block(n, named_ret_var);
      --indent_;
      emit_indent();
      out_ << "}\n";
    } else if (n.kind == NodeKind::ExpressionStatement) {
      // Remove trailing semicolon if present in node_text to avoid double
      // semicolon Actually, we should call emit_expression for consistency But
      // node_text might include the semicolon if it was parsed as
      // ExpressionStatement Let's rely on emit_expression + ";"
      for (const auto &child : tree_.children(n)) {
        if (meta::is_expression(child.kind)) {
          emit_expression(child);
          out_ << ";\n";
          return;
        }
      }
      // Fallback
      out_ << node_text(n) << "\n";
    } else if (n.kind == NodeKind::Statement) {
      // Generic statement - check children
      for (const auto &child : tree_.children(n)) {
        emit_statement(child, named_ret_var);
      }
    } else if (n.kind == NodeKind::UnifiedDeclaration) {
      // Local variable
      emit_local_var(n);
    } else {
      out_ << node_text(n) << ";\n";
    }
  }

  void emit_if(const Node &n, const std::string &named_ret_var = "") {
    out_ << "if (";
    bool first = true;
    for (const auto &child : tree_.children(n)) {
      if (first && child.kind != NodeKind::BlockStatement &&
          child.kind != NodeKind::Statement) {
        out_ << node_text(child);
        first = false;
      } else if (child.kind == NodeKind::BlockStatement) {
        out_ << ") {\n";
        ++indent_;
        emit_block(child, named_ret_var);
        --indent_;
        emit_indent();
        out_ << "}";
      }
    }
    out_ << "\n";
  }

  void emit_while(const Node &n, const std::string &named_ret_var = "") {
    out_ << "while (";
    bool first = true;
    for (const auto &child : tree_.children(n)) {
      if (first && child.kind != NodeKind::BlockStatement) {
        out_ << node_text(child);
        first = false;
      } else if (child.kind == NodeKind::BlockStatement) {
        out_ << ") {\n";
        ++indent_;
        emit_block(child, named_ret_var);
        --indent_;
        emit_indent();
        out_ << "} \n";
      }
    }
  }

  void emit_for(const Node &n, const std::string &named_ret_var = "") {
    // Cpp2 for: for items do (item) { body }
    // C++1 for: for (item : items) { body }
    // Both emit as: for (auto item : items) { body }
    std::string items, var;
    const Node *body = nullptr;

    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::BlockStatement) {
        body = &child;
      } else if (child.kind == NodeKind::Identifier ||
                 (child.kind == NodeKind::Parameter && var.empty())) {
        var = node_text(child);
      } else if (meta::is_expression(child.kind) && items.empty()) {
        // Only use expression nodes for items (skip keywords, punctuation)
        items = node_text(child);
      }
    }

    out_ << "for (auto " << var << " : " << items << ") {\n";
    ++indent_;
    if (body)
      emit_block(*body, named_ret_var);
    --indent_;
    emit_indent();
    out_ << "}\n";
  }

  void emit_local_var(const Node &n) {
    std::string name;
    std::string type = "auto";
    const Node *init_expr = nullptr;

    // Look for Identifier child first
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
        break;
      }
    }
    // Fallback to first token if no Identifier child
    if (name.empty()) {
      name = std::string(token_text(n.token_start));
    }

    // Check for children
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::VariableSuffix) {
        // Inside VariableSuffix: [TypeSpecifier] [= Expression] ;
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::TypeSpecifier ||
              grandchild.kind == NodeKind::BasicType) {
            type = format_type(grandchild);
          } else if (meta::is_expression(grandchild.kind)) {
            init_expr = &grandchild;
          }
        }
      } else if (child.kind == NodeKind::TypeSpecifier ||
                 child.kind == NodeKind::BasicType) {
        // Handle direct type specifier (parser quirk/bug workaround)
        type = format_type(child);
      } else if (meta::is_expression(child.kind)) {
        // Direct expression child means := deduction
        init_expr = &child;
      }
    }

    out_ << type << " " << name;
    if (init_expr) {
      out_ << " = ";
      emit_initializer(*init_expr);
    }
    out_ << ";\n";
  }

  void emit_variable(const std::string &name, const Node &suffix) {
    // Global variable (from emit_unified_decl)
    emit_indent();

    std::string type = "auto";
    const Node *init_expr = nullptr;

    // Suffix might be VariableSuffix, or UnifiedDeclaration logic might have
    // passed the suffix node But emit_unified_decl passes the child node.

    // If suffix is VariableSuffix:
    if (suffix.kind == NodeKind::VariableSuffix) {
      for (const auto &child : tree_.children(suffix)) {
        if (child.kind == NodeKind::TypeSpecifier ||
            child.kind == NodeKind::QualifiedType ||
            child.kind == NodeKind::BasicType) {
          type = format_type(child);
        } else if (meta::is_expression(child.kind)) {
          init_expr = &child;
        }
      }
    } else {
      // Check direct children of the suffix node (whatever it is)
      for (const auto &child : tree_.children(suffix)) {
        if (child.kind == NodeKind::TypeSpecifier ||
            child.kind == NodeKind::QualifiedType ||
            child.kind == NodeKind::BasicType) {
          type = format_type(child);
        } else if (meta::is_expression(child.kind)) {
          init_expr = &child;
        }
      }
    }

    out_ << type << " " << name;
    if (init_expr) {
      out_ << " = ";
      emit_initializer(*init_expr);
    }
    out_ << ";\n";
  }

  // Emit an initializer expression, converting (a,b,c) tuple syntax to {a,b,c}
  void emit_initializer(const Node &n) {
    std::string text = trim(node_text(n));
    // Check if it's empty parens () -> brace init {}
    if (text == "()") {
      out_ << "{}";
      return;
    }
    // Check if it's a parenthesized expression with commas (tuple initializer)
    if (!text.empty() && text.front() == '(' && text.back() == ')' &&
        text.find(',') != std::string::npos) {
      // Replace outer () with {} for brace initialization
      // Text is like "(1, 2, 3)" -> "{1, 2, 3}"
      out_ << "{" << text.substr(1, text.length() - 2) << "}";
      return;
    }
    // Default: emit as regular expression
    emit_expression(n);
  }

  void emit_type(const std::string &name, const Node &suffix) {
    out_ << "struct " << name << " {\n";
    ++indent_;
    
    // Find the TypeBody child and emit its declarations
    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::TypeBody) {
        emit_type_body(child, name);
      }
    }
    
    --indent_;
    out_ << "};\n\n";
  }
  
  void emit_type_body(const Node &body, const std::string &type_name) {
    // TypeBody contains Declaration nodes
    for (const auto &child : tree_.children(body)) {
      if (child.kind == NodeKind::Declaration) {
        emit_type_member(child, type_name);
      }
    }
  }
  
  void emit_type_member(const Node &decl, const std::string &type_name) {
    // Get the member name and determine if it's a field or method
    for (const auto &child : tree_.children(decl)) {
      if (child.kind == NodeKind::UnifiedDeclaration) {
        std::string member_name;
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::Identifier) {
            member_name = node_text(grandchild);
            break;
          }
        }
        if (member_name.empty()) {
          member_name = std::string(token_text(child.token_start));
        }
        
        // Check if it's a function (method) or variable (field)
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::FunctionSuffix) {
            emit_method(member_name, grandchild, type_name);
            return;
          }
          if (grandchild.kind == NodeKind::VariableSuffix) {
            emit_field(member_name, grandchild);
            return;
          }
        }
      }
    }
  }
  
  void emit_method(const std::string &name, const Node &suffix, const std::string &type_name) {
    // Similar to emit_function but for methods
    std::string return_type = "auto";
    std::string params;
    const Node *body = nullptr;
    bool is_static = false;
    
    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::ParamList) {
        // Check for 'this' parameter to determine static vs non-static
        for (const auto &param : tree_.children(child)) {
          if (param.kind == NodeKind::Parameter) {
            std::string param_text = node_text(param);
            if (param_text.find("this") != std::string::npos) {
              is_static = false;
            }
          }
        }
        params = emit_params(child);
      } else if (child.kind == NodeKind::ReturnSpec) {
        return_type = emit_type_spec(child);
      } else if (child.kind == NodeKind::FunctionBody) {
        body = &child;
      }
    }
    
    // Check for named return type
    std::string named_return_type = extract_named_return_type(return_type);
    if (!named_return_type.empty()) {
      return_type = named_return_type;  // Use the actual type for methods
    }
    
    // Infer void return type when no explicit return
    if (return_type == "auto" && !function_has_return_value(suffix)) {
      return_type = "void";
    }
    
    emit_indent();
    if (is_static) {
      out_ << "static ";
    }
    out_ << "auto " << name << "(" << params << ") -> " << return_type << " {\n";
    
    ++indent_;
    if (body)
      emit_function_body(*body);
    --indent_;
    
    emit_indent();
    out_ << "}\n";
  }
  
  void emit_field(const std::string &name, const Node &suffix) {
    std::string type = "auto";
    std::string init;
    
    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::TypeSpecifier || child.kind == NodeKind::BasicType) {
        type = format_type(child);
      } else if (meta::is_expression(child.kind)) {
        init = node_text(child);
      }
    }
    
    emit_indent();
    out_ << type << " " << name;
    if (!init.empty()) {
      out_ << " = " << init;
    }
    out_ << ";\n";
  }

  bool is_infix_expression(NodeKind k) const {
    using K = NodeKind;
    if (k < K::MultiplicativeExpression || k > K::AssignmentExpression)
      return false;
    return k != K::TernaryExpression && k != K::PipelineExpression &&
           k != K::RangeExpression && k != K::AssignmentOp;
  }

  void emit_expression(const Node &n) {
    if (n.kind == NodeKind::Identifier || n.kind == NodeKind::Literal) {
      out_ << node_text(n);
    } else if (n.kind == NodeKind::Expression) {
      for (const auto &child : tree_.children(n)) {
        emit_expression(child);
      }
    } else if (n.kind == NodeKind::AssignmentExpression) {
      std::vector<const Node *> children;
      for (const auto &child : tree_.children(n))
        children.push_back(&child);

      if (children.size() >= 3 && token_text(children[0]->token_start) == "_") {
        out_ << "(void)(";
        emit_expression(*children[2]);
        out_ << ")";
      } else {
        for (const auto *child : children) {
          if (child->kind == NodeKind::AssignmentOp ||
              child->kind == NodeKind::BinaryOp ||
              (child->token_start < child->token_end &&
               is_operator(token_text(child->token_start)))) {
            out_ << " " << node_text(*child) << " ";
          } else {
            emit_expression(*child);
          }
        }
      }
    } else if (is_infix_expression(n.kind)) {
      for (const auto &child : tree_.children(n)) {
        if (child.kind == NodeKind::BinaryOp ||
            child.kind == NodeKind::AssignmentOp ||
            (child.token_start < child.token_end &&
             is_operator(token_text(child.token_start)))) {
          std::string op = node_text(child);
          if (op == ",") {
            out_ << ", "; // comma: no leading space
          } else {
            out_ << " " << op << " ";
          }
        } else {
          emit_expression(child);
        }
      }

    } else if (n.kind == NodeKind::CallOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        const Node &callee = *it;
        ++it;
        
        // Check if this is a UFCS call (obj.method(args) -> CPP2_UFCS(method)(obj, args))
        // But NOT if it's explicit member access with .. (double dot)
        if (callee.kind == NodeKind::MemberOp) {
          // Check if the MemberOp contains ".." token (explicit member, not UFCS)
          bool is_explicit_member = node_contains_token(callee, "..");
          
          if (!is_explicit_member) {
            // UFCS: obj.method(args) should become CPP2_UFCS(method)(obj, args)
            auto member_children = tree_.children(callee);
            auto member_it = member_children.begin();
            
            if (member_it != member_children.end()) {
              const Node &obj = *member_it;
              ++member_it;
              
              // Get the method name
              std::string method_name;
              for (; member_it != member_children.end(); ++member_it) {
                if (member_it->kind == NodeKind::Identifier) {
                  method_name = node_text(*member_it);
                  break;
                }
              }
              
              if (!method_name.empty()) {
                // Emit: CPP2_UFCS(method)(obj, args...)
                out_ << "CPP2_UFCS(" << method_name << ")(";
                emit_expression(obj);
                for (; it != children.end(); ++it) {
                  out_ << ", ";
                  emit_expression(*it);
                }
                out_ << ")";
                return;
              }
            }
          }
          // Explicit member call (..): fall through to emit as regular call
        }
        
        // Not UFCS - regular function call
        emit_expression(callee);
        out_ << "(";
        bool first = true;
        for (; it != children.end(); ++it) {
          if (!first)
            out_ << ", ";
          emit_expression(*it);
          first = false;
        }
        out_ << ")";
      } else {
        // Sibling fallback
        out_ << "(";
        bool first = true;
        for (const auto &child : children) {
          if (!first)
            out_ << ", ";
          emit_expression(child);
          first = false;
        }
        out_ << ")";
      }
    } else if (n.kind == NodeKind::MemberOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee (LHS)
        ++it;
        // In hierarchical mode, start_infix was called at the operator.
        // n.token_start is the operator token.
        std::string op = std::string(token_text(n.token_start));
        // Handle :: (scope), . (member), and .. (explicit member - emit as single .)
        if (op == "::") {
          out_ << "::";
        } else {
          // Both . and .. emit as single . in C++
          out_ << ".";
        }
        for (; it != children.end(); ++it) {
          if (it->kind == NodeKind::Identifier)
            out_ << node_text(*it);
          else
            emit_expression(*it);
        }
      } else {
        // Sibling fallback
        std::string op = std::string(token_text(n.token_start));
        out_ << (op == "::" ? "::" : ".");
        for (const auto &child : children) {
          out_ << node_text(child);
        }
      }
    } else if (n.kind == NodeKind::ScopeOp) {
      // Scope resolution operator :: (e.g., std::cout)
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee (LHS - namespace or class)
        ++it;
        out_ << "::";
        for (; it != children.end(); ++it) {
          if (it->kind == NodeKind::Identifier)
            out_ << node_text(*it);
          else
            emit_expression(*it);
        }
      } else {
        // Sibling fallback
        out_ << "::";
        for (const auto &child : children) {
          out_ << node_text(child);
        }
      }
    } else if (n.kind == NodeKind::TemplateArgs) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee
        ++it;
        out_ << "<";
        bool first = true;
        for (; it != children.end(); ++it) {
          if (!first)
            out_ << ", ";
          if (it->kind == NodeKind::TypeSpecifier ||
              it->kind == NodeKind::QualifiedType ||
              it->kind == NodeKind::BasicType) {
            out_ << format_type(*it);
          } else {
            emit_expression(*it);
          }
          first = false;
        }
        out_ << ">";
      } else {
        out_ << "<";
        bool first = true;
        for (const auto &child : children) {
          if (!first)
            out_ << ", ";
          emit_expression(child);
          first = false;
        }
        out_ << ">";
      }
    } else if (n.kind == NodeKind::TypeSpecifier ||
               n.kind == NodeKind::QualifiedType) {
      out_ << format_type(n);
    } else if (n.kind == NodeKind::SubscriptOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee
        ++it;
        out_ << "[";
        for (; it != children.end(); ++it) {
          emit_expression(*it);
        }
        out_ << "]";
      } else {
        out_ << "[";
        for (const auto &child : children) {
          emit_expression(child);
        }
        out_ << "]";
      }
    } else if (n.kind == NodeKind::PostfixOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        const Node &lhs = *it;
        ++it;
        if (it != children.end()) {
          std::string op = node_text(*it);
          if (op == "*") {
            out_ << "*(";
            emit_expression(lhs);
            out_ << ")";
          } else if (op == "&") {
            out_ << "&(";
            emit_expression(lhs);
            out_ << ")";
          } else {
            emit_expression(lhs);
            out_ << op;
          }
        } else {
          out_ << node_text(n);
        }
      } else {
        out_ << node_text(n);
      }
    } else if (n.kind == NodeKind::TernaryExpression) {
      out_ << " ? ";
      int i = 0;
      for (const auto &child : tree_.children(n)) {
        if (i == 1)
          out_ << " : ";
        emit_expression(child);
        i++;
      }
    } else if (n.kind == NodeKind::GroupedExpression) {
      out_ << "(";
      for (const auto &child : tree_.children(n)) {
        emit_expression(child);
      }
      out_ << ")";
    } else if (n.kind == NodeKind::PrefixExpression) {
      for (const auto &child : tree_.children(n)) {
        if (child.kind == NodeKind::PrefixOp) {
          out_ << node_text(child);
        } else {
          emit_expression(child);
        }
      }
    } else {
      // Fallback
      out_ << node_text(n);
    }
  }

  bool is_operator(std::string_view s) const {
    return s.find_first_not_of("+-*/%&|^<>=!~") == std::string_view::npos ||
           s == "and" || s == "or" || s == "not";
  }

  void emit_namespace(const std::string &name, const Node &suffix) {
    out_ << "namespace " << name << " {\n\n";
    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::NamespaceBody) {
        for (const auto &decl : tree_.children(child)) {
          emit_declaration(decl);
        }
      }
    }
    out_ << "} // namespace " << name << "\n\n";
  }
};

} // anonymous namespace

std::string generate_from_tree(const cpp2::ast::ParseTree &tree,
                               std::span<const cpp2_transpiler::Token> tokens) {
  TreeEmitter emitter(tree, tokens);
  return emitter.emit();
}
