#include "emitter.hpp"
#include <cctype>
#include <iostream>
#include <sstream>
#include <vector>

namespace {

using namespace cpp2::ast;

class TreeEmitter {
  const ParseTree &tree_;
  std::span<const cpp2_transpiler::Token> tokens_;
  std::ostringstream out_;
  int indent_ = 0;

  void emit_indent() {
    for (int i = 0; i < indent_; ++i)
      out_ << "    ";
  }

  std::string_view token_text(uint32_t idx) const {
    if (idx < tokens_.size())
      return tokens_[idx].lexeme;
    return "";
  }

  std::string node_text(const Node &n) const {
    std::string result;
    for (uint32_t i = n.token_start; i < n.token_end && i < tokens_.size();
         ++i) {
      if (!result.empty() && !tokens_[i].lexeme.empty()) {
        char prev = result.back();
        char next = tokens_[i].lexeme[0];
        if (std::isalnum(prev) && std::isalnum(next))
          result += ' ';
      }
      result += tokens_[i].lexeme;
    }
    return result;
  }

  std::string map_type_name(const std::string &name) const {
    if (name == "i32")
      return "int";
    if (name == "u32")
      return "unsigned int";
    if (name == "i16")
      return "int16_t";
    if (name == "u16")
      return "uint16_t";
    if (name == "i8")
      return "int8_t";
    if (name == "u8")
      return "uint8_t";
    if (name == "i64")
      return "int64_t";
    if (name == "u64")
      return "uint64_t";
    if (name == "f32")
      return "float";
    if (name == "f64")
      return "double";
    return name;
  }

  std::string trim(std::string_view s) const {
    size_t first = s.find_first_not_of(" \t\n\r");
    if (first == std::string::npos)
      return "";
    size_t last = s.find_last_not_of(" \t\n\r");
    return std::string(s.substr(first, last - first + 1));
  }

  std::string format_type(const Node &n) const {
    std::string text = trim(node_text(n));
    // Simple heuristic: move leading * and & to the end
    size_t i = 0;
    std::string qualifiers;
    while (i < text.length() && (text[i] == '*' || text[i] == '&')) {
      qualifiers += text[i];
      i++;
    }
    std::string base = trim(text.substr(i));
    return map_type_name(base) + qualifiers;
  }

public:
  TreeEmitter(const ParseTree &tree,
              std::span<const cpp2_transpiler::Token> tokens)
      : tree_(tree), tokens_(tokens) {}

  std::string emit() {
    out_ << "// Generated by cppfort - slim ParseTree emitter\n";
    out_ << "#include <iostream>\n";
    out_ << "#include <string>\n";
    out_ << "#include <cstdint>\n\n";

    if (tree_.nodes.empty())
      return out_.str();

    const auto &root = tree_[tree_.root];
    for (const auto &child : tree_.children(root)) {
      emit_declaration(child);
    }

    return out_.str();
  }

private:
  void emit_declaration(const Node &n) {
    if (n.kind != NodeKind::Declaration)
      return;

    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::UnifiedDeclaration) {
        emit_unified_decl(child);
      } else if (child.kind == NodeKind::FunctionSuffix) {
        // C++1 function declaration: auto name() -> type { body }
        // Find the identifier name from inside the FunctionSuffix
        std::string name = "unknown";
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::Identifier) {
            name = node_text(grandchild);
            break;
          }
        }
        emit_function(name, child);
      }
    }
  }

  void emit_unified_decl(const Node &n) {
    // Try to find identifier name from children first (for C++1 functions)
    std::string name;
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
        break;
      }
    }
    // Fallback to first token for Cpp2 declarations
    if (name.empty()) {
      name = std::string(token_text(n.token_start));
    }

    // Check for function suffix vs variable suffix
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::FunctionSuffix) {
        emit_function(name, child);
        return;
      }
      if (child.kind == NodeKind::VariableSuffix) {
        emit_variable(name, child);
        return;
      }
      if (child.kind == NodeKind::TypeSuffix) {
        emit_type(name, child);
        return;
      }
      if (child.kind == NodeKind::NamespaceSuffix) {
        emit_namespace(name, child);
        return;
      }
    }

    // Fallback: simple variable with := initialization
    emit_indent();
    // Check if we have an expression child for initialization
    std::string init;
    for (const auto &child : tree_.children(n)) {
      if (meta::is_expression(child.kind) ||
          child.kind == NodeKind::AssignmentExpression) {
        init = node_text(child);
        break;
      }
    }

    if (!init.empty()) {
      out_ << "auto " << name << " = " << init << ";\n";
    } else {
      out_ << "auto " << name << "; // TODO: Unknown decl\n";
    }
  }

  void emit_function(const std::string &name, const Node &suffix) {
    // Extract return type (if any) and parameters
    std::string return_type = "auto";
    std::string params;
    const Node *body = nullptr;

    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::ParamList) {
        params = emit_params(child);
      } else if (child.kind == NodeKind::ReturnSpec) {
        return_type = emit_type_spec(child);
      } else if (child.kind == NodeKind::FunctionBody) {
        body = &child;
      }
    }

    // Handle main function specially (only for Cpp2 syntax without explicit
    // return)
    if (name == "main" && return_type == "auto") {
      out_ << "int main(int argc, char* argv[]) {\n";
    } else {
      out_ << "auto " << name << "(" << params << ") -> " << return_type
           << " {\n";
    }

    ++indent_;
    if (body)
      emit_function_body(*body);
    --indent_;

    out_ << "}\n\n";
  }

  std::string emit_params(const Node &n) {
    std::string result;
    for (const auto &param : tree_.children(n)) {
      if (param.kind == NodeKind::Parameter) {
        if (!result.empty())
          result += ", ";
        result += emit_param(param);
      }
    }
    return result;
  }

  std::string emit_param(const Node &n) {
    // Get param name and optional type
    std::string name;
    std::string type = "auto";
    std::string qualifier; // inout, out, in, etc.

    // Check children for qualifier and type
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::ParamQualifier) {
        qualifier = node_text(child);
      } else if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
      } else if (child.kind == NodeKind::TypeSpecifier ||
                 child.kind == NodeKind::BasicType) {
        type = format_type(child);
      }
    }

    if (name.empty()) {
      // Fallback for cases where identifier might not be wrapped (legacy or
      // specific patterns) But be careful not to pick up qualifier if it exists
      if (!qualifier.empty()) {
        // If we have qualifier, token_start is qualifier. name must be later.
        // We should rely on children. If identifier node is missing, maybe it's
        // implicit or failed parse? Assuming parser always produces Identifier
        // node for name now. If fallback needed, maybe skip qualifier tokens?
        // For now, trust Identifier node.
      } else {
        name = std::string(token_text(n.token_start));
      }
    }

    // Apply qualifiers to type
    std::string result_type = type;
    if (!qualifier.empty()) {
      if (qualifier == "inout" || qualifier == "out") {
        // Reference parameter
        if (type == "auto") {
          result_type = "auto&";
        } else {
          result_type = type + "&";
        }
      } else if (qualifier == "move") {
        // Rvalue reference
        if (type == "auto") {
          result_type = "auto&&";
        } else {
          result_type = type + "&&";
        }
      } else if (qualifier == "forward") {
        // Forwarding reference
        if (type == "auto") {
          result_type = "auto&&";
        } else {
          result_type = type + "&&";
        }
      } else if (qualifier == "in") {
        // Const reference
        if (type == "auto") {
          result_type = "const auto&";
        } else {
          result_type = "const " + type + "&";
        }
      }
      // "copy" (value) is default, no change needed
    }

    return result_type + " " + name;
  }

  std::string emit_type_spec(const Node &n) {
    // Return spec has arrow -> type
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::TypeSpecifier ||
          child.kind == NodeKind::BasicType) {
        return format_type(child);
      }
    }
    // Fallback: get text after ->
    std::string text = node_text(n);
    auto pos = text.find("->");
    if (pos != std::string::npos) {
      std::string result = text.substr(pos + 2);
      // Trim whitespace
      while (!result.empty() && std::isspace(result.front()))
        result.erase(0, 1);
      return result.empty() ? "auto" : result;
    }
    return "auto";
  }

  void emit_function_body(const Node &n) {
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::BlockStatement) {
        emit_block(child);
      } else {
        // Expression body: = expr;
        emit_indent();
        out_ << "return " << node_text(child) << ";\n";
      }
    }
  }

  void emit_block(const Node &n) {
    for (const auto &child : tree_.children(n)) {
      emit_statement(child);
    }
  }

  void emit_statement(const Node &n) {
    emit_indent();

    if (n.kind == NodeKind::ReturnStatement) {
      out_ << "return";
      for (const auto &child : tree_.children(n)) {
        out_ << " " << node_text(child);
      }
      out_ << ";\n";
    } else if (n.kind == NodeKind::IfStatement) {
      emit_if(n);
    } else if (n.kind == NodeKind::WhileStatement) {
      emit_while(n);
    } else if (n.kind == NodeKind::ForStatement) {
      emit_for(n);
    } else if (n.kind == NodeKind::BlockStatement) {
      out_ << "{\n";
      ++indent_;
      emit_block(n);
      --indent_;
      emit_indent();
      out_ << "}\n";
    } else if (n.kind == NodeKind::ExpressionStatement) {
      // Remove trailing semicolon if present in node_text to avoid double
      // semicolon Actually, we should call emit_expression for consistency But
      // node_text might include the semicolon if it was parsed as
      // ExpressionStatement Let's rely on emit_expression + ";"
      for (const auto &child : tree_.children(n)) {
        if (meta::is_expression(child.kind)) {
          emit_expression(child);
          out_ << ";\n";
          return;
        }
      }
      // Fallback
      out_ << node_text(n) << "\n";
    } else if (n.kind == NodeKind::Statement) {
      // Generic statement - check children
      for (const auto &child : tree_.children(n)) {
        emit_statement(child);
      }
    } else if (n.kind == NodeKind::UnifiedDeclaration) {
      // Local variable
      emit_local_var(n);
    } else {
      out_ << node_text(n) << ";\n";
    }
  }

  void emit_if(const Node &n) {
    out_ << "if (";
    bool first = true;
    for (const auto &child : tree_.children(n)) {
      if (first && child.kind != NodeKind::BlockStatement &&
          child.kind != NodeKind::Statement) {
        out_ << node_text(child);
        first = false;
      } else if (child.kind == NodeKind::BlockStatement) {
        out_ << ") {\n";
        ++indent_;
        emit_block(child);
        --indent_;
        emit_indent();
        out_ << "}";
      }
    }
    out_ << "\n";
  }

  void emit_while(const Node &n) {
    out_ << "while (";
    bool first = true;
    for (const auto &child : tree_.children(n)) {
      if (first && child.kind != NodeKind::BlockStatement) {
        out_ << node_text(child);
        first = false;
      } else if (child.kind == NodeKind::BlockStatement) {
        out_ << ") {\n";
        ++indent_;
        emit_block(child);
        --indent_;
        emit_indent();
        out_ << "} \n";
      }
    }
  }

  void emit_for(const Node &n) {
    // Cpp2 for: for items do (item) { body }
    // C++1 for: for (item : items) { body }
    // Both emit as: for (auto item : items) { body }
    std::string items, var;
    const Node *body = nullptr;

    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::BlockStatement) {
        body = &child;
      } else if (child.kind == NodeKind::Identifier ||
                 (child.kind == NodeKind::Parameter && var.empty())) {
        var = node_text(child);
      } else if (meta::is_expression(child.kind) && items.empty()) {
        // Only use expression nodes for items (skip keywords, punctuation)
        items = node_text(child);
      }
    }

    out_ << "for (auto " << var << " : " << items << ") {\n";
    ++indent_;
    if (body)
      emit_block(*body);
    --indent_;
    emit_indent();
    out_ << "}\n";
  }

  void emit_local_var(const Node &n) {
    std::string name;
    std::string type = "auto";
    const Node *init_expr = nullptr;

    // Look for Identifier child first
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::Identifier) {
        name = node_text(child);
        break;
      }
    }
    // Fallback to first token if no Identifier child
    if (name.empty()) {
      name = std::string(token_text(n.token_start));
    }

    // Check for children
    for (const auto &child : tree_.children(n)) {
      if (child.kind == NodeKind::VariableSuffix) {
        // Inside VariableSuffix: [TypeSpecifier] [= Expression] ;
        for (const auto &grandchild : tree_.children(child)) {
          if (grandchild.kind == NodeKind::TypeSpecifier ||
              grandchild.kind == NodeKind::BasicType) {
            type = node_text(grandchild);
          } else if (meta::is_expression(grandchild.kind)) {
            init_expr = &grandchild;
          }
        }
      } else if (child.kind == NodeKind::TypeSpecifier ||
                 child.kind == NodeKind::BasicType) {
        // Handle direct type specifier (parser quirk/bug workaround)
        type = node_text(child);
      } else if (meta::is_expression(child.kind)) {
        // Direct expression child means := deduction
        init_expr = &child;
      }
    }

    out_ << type << " " << name;
    if (init_expr) {
      out_ << " = ";
      emit_expression(*init_expr);
    }
    out_ << ";\n";
  }

  void emit_variable(const std::string &name, const Node &suffix) {
    // Global variable (from emit_unified_decl)
    emit_indent();

    std::string type = "auto";
    const Node *init_expr = nullptr;

    // Suffix might be VariableSuffix, or UnifiedDeclaration logic might have
    // passed the suffix node But emit_unified_decl passes the child node.

    // If suffix is VariableSuffix:
    if (suffix.kind == NodeKind::VariableSuffix) {
      for (const auto &child : tree_.children(suffix)) {
        if (child.kind == NodeKind::TypeSpecifier ||
            child.kind == NodeKind::QualifiedType ||
            child.kind == NodeKind::BasicType) {
          type = format_type(child);
        } else if (meta::is_expression(child.kind)) {
          init_expr = &child;
        }
      }
    } else {
      // Check direct children of the suffix node (whatever it is)
      for (const auto &child : tree_.children(suffix)) {
        if (child.kind == NodeKind::TypeSpecifier ||
            child.kind == NodeKind::QualifiedType ||
            child.kind == NodeKind::BasicType) {
          type = format_type(child);
        } else if (meta::is_expression(child.kind)) {
          init_expr = &child;
        }
      }
    }

    out_ << type << " " << name;
    if (init_expr) {
      out_ << " = ";
      emit_expression(*init_expr);
    }
    out_ << ";\n";
  }

  void emit_type(const std::string &name, const Node & /*suffix*/) {
    out_ << "struct " << name << " {\n";
    out_ << "    // TODO: type body\n";
    out_ << "};\n\n";
  }

  bool is_infix_expression(NodeKind k) const {
    using K = NodeKind;
    if (k < K::MultiplicativeExpression || k > K::AssignmentExpression)
      return false;
    return k != K::TernaryExpression && k != K::PipelineExpression &&
           k != K::RangeExpression && k != K::AssignmentOp;
  }

  void emit_expression(const Node &n) {
    if (n.kind == NodeKind::Identifier || n.kind == NodeKind::Literal) {
      out_ << node_text(n);
    } else if (n.kind == NodeKind::Expression) {
      for (const auto &child : tree_.children(n)) {
        emit_expression(child);
      }
    } else if (n.kind == NodeKind::AssignmentExpression) {
      std::vector<const Node *> children;
      for (const auto &child : tree_.children(n))
        children.push_back(&child);

      if (children.size() >= 3 && token_text(children[0]->token_start) == "_") {
        out_ << "(void)(";
        emit_expression(*children[2]);
        out_ << ")";
      } else {
        for (const auto *child : children) {
          if (child->kind == NodeKind::AssignmentOp ||
              child->kind == NodeKind::BinaryOp ||
              (child->token_start < child->token_end &&
               is_operator(token_text(child->token_start)))) {
            out_ << " " << node_text(*child) << " ";
          } else {
            emit_expression(*child);
          }
        }
      }
    } else if (is_infix_expression(n.kind)) {
      for (const auto &child : tree_.children(n)) {
        if (child.kind == NodeKind::BinaryOp ||
            child.kind == NodeKind::AssignmentOp ||
            (child.token_start < child.token_end &&
             is_operator(token_text(child.token_start)))) {
          std::string op = node_text(child);
          if (op == ",") {
            out_ << ", "; // comma: no leading space
          } else {
            out_ << " " << op << " ";
          }
        } else {
          emit_expression(child);
        }
      }

    } else if (n.kind == NodeKind::CallOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee (Function name)
        ++it;
        out_ << "(";
        bool first = true;
        for (; it != children.end(); ++it) {
          if (!first)
            out_ << ", ";
          emit_expression(*it);
          first = false;
        }
        out_ << ")";
      } else {
        // Sibling fallback
        out_ << "(";
        bool first = true;
        for (const auto &child : children) {
          if (!first)
            out_ << ", ";
          emit_expression(child);
          first = false;
        }
        out_ << ")";
      }
    } else if (n.kind == NodeKind::MemberOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee (LHS)
        ++it;
        // In hierarchical mode, start_infix was called at the operator.
        // n.token_start is the operator token.
        std::string op = std::string(token_text(n.token_start));
        out_ << (op == "::" ? "::" : ".");
        for (; it != children.end(); ++it) {
          if (it->kind == NodeKind::Identifier)
            out_ << node_text(*it);
          else
            emit_expression(*it);
        }
      } else {
        // Sibling fallback
        std::string op = std::string(token_text(n.token_start));
        out_ << (op == "::" ? "::" : ".");
        for (const auto &child : children) {
          out_ << node_text(child);
        }
      }
    } else if (n.kind == NodeKind::ScopeOp) {
      // Scope resolution operator :: (e.g., std::cout)
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee (LHS - namespace or class)
        ++it;
        out_ << "::";
        for (; it != children.end(); ++it) {
          if (it->kind == NodeKind::Identifier)
            out_ << node_text(*it);
          else
            emit_expression(*it);
        }
      } else {
        // Sibling fallback
        out_ << "::";
        for (const auto &child : children) {
          out_ << node_text(child);
        }
      }
    } else if (n.kind == NodeKind::TemplateArgs) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee
        ++it;
        out_ << "<";
        bool first = true;
        for (; it != children.end(); ++it) {
          if (!first)
            out_ << ", ";
          if (it->kind == NodeKind::TypeSpecifier ||
              it->kind == NodeKind::QualifiedType ||
              it->kind == NodeKind::BasicType) {
            out_ << format_type(*it);
          } else {
            emit_expression(*it);
          }
          first = false;
        }
        out_ << ">";
      } else {
        out_ << "<";
        bool first = true;
        for (const auto &child : children) {
          if (!first)
            out_ << ", ";
          emit_expression(child);
          first = false;
        }
        out_ << ">";
      }
    } else if (n.kind == NodeKind::TypeSpecifier ||
               n.kind == NodeKind::QualifiedType) {
      out_ << format_type(n);
    } else if (n.kind == NodeKind::SubscriptOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        emit_expression(*it); // Adoptee
        ++it;
        out_ << "[";
        for (; it != children.end(); ++it) {
          emit_expression(*it);
        }
        out_ << "]";
      } else {
        out_ << "[";
        for (const auto &child : children) {
          emit_expression(child);
        }
        out_ << "]";
      }
    } else if (n.kind == NodeKind::PostfixOp) {
      auto children = tree_.children(n);
      auto it = children.begin();
      if (it != children.end()) {
        const Node &lhs = *it;
        ++it;
        if (it != children.end()) {
          std::string op = node_text(*it);
          if (op == "*") {
            out_ << "*(";
            emit_expression(lhs);
            out_ << ")";
          } else if (op == "&") {
            out_ << "&(";
            emit_expression(lhs);
            out_ << ")";
          } else {
            emit_expression(lhs);
            out_ << op;
          }
        } else {
          out_ << node_text(n);
        }
      } else {
        out_ << node_text(n);
      }
    } else if (n.kind == NodeKind::TernaryExpression) {
      out_ << " ? ";
      int i = 0;
      for (const auto &child : tree_.children(n)) {
        if (i == 1)
          out_ << " : ";
        emit_expression(child);
        i++;
      }
    } else if (n.kind == NodeKind::GroupedExpression) {
      out_ << "(";
      for (const auto &child : tree_.children(n)) {
        emit_expression(child);
      }
      out_ << ")";
    } else if (n.kind == NodeKind::PrefixExpression) {
      for (const auto &child : tree_.children(n)) {
        if (child.kind == NodeKind::PrefixOp) {
          out_ << node_text(child);
        } else {
          emit_expression(child);
        }
      }
    } else {
      // Fallback
      out_ << node_text(n);
    }
  }

  bool is_operator(std::string_view s) const {
    return s.find_first_not_of("+-*/%&|^<>=!~") == std::string_view::npos ||
           s == "and" || s == "or" || s == "not";
  }

  void emit_namespace(const std::string &name, const Node &suffix) {
    out_ << "namespace " << name << " {\n\n";
    for (const auto &child : tree_.children(suffix)) {
      if (child.kind == NodeKind::NamespaceBody) {
        for (const auto &decl : tree_.children(child)) {
          emit_declaration(decl);
        }
      }
    }
    out_ << "} // namespace " << name << "\n\n";
  }
};

} // anonymous namespace

std::string generate_from_tree(const cpp2::ast::ParseTree &tree,
                               std::span<const cpp2_transpiler::Token> tokens) {
  TreeEmitter emitter(tree, tokens);
  return emitter.emit();
}
